import {
  Activity,
  BarChart3,
  Bot,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  Clock3,
  CreditCard,
  FileCheck2,
  FileText,
  Fuel,
  Gauge,
  Landmark,
  Map,
  MapPinned,
  PackageCheck,
  RadioTower,
  Route,
  ScrollText,
  Settings,
  ShieldAlert,
  Siren,
  TrendingDown,
  Truck,
  UserCog,
  Users,
  Video,
  WalletCards,
  Wrench,
  Zap,
} from "lucide-react";
import type { ModuleConfig } from "@/types";

export const modules: ModuleConfig[] = [
  { key: "command-center", title: "Command Center", route: "/command-center", group: "Command", description: "Executive operating picture, AI brief, live risk posture and command actions.", accent: "teal" },
  { key: "control-tower", title: "Live Map / Control Tower", route: "/control-tower", group: "Command", description: "Simulated live map, vehicle pins, geofences, exceptions and event stream.", accent: "blue" },
  { key: "dispatch", title: "Dispatch Board", route: "/dispatch", group: "Dispatch", description: "Kanban dispatch board, AI matching, driver and vehicle assignment workflow.", accent: "teal" },
  { key: "jobs", title: "Jobs & Orders", route: "/jobs", group: "Dispatch", description: "Orders, SLA, ETA, pickup/drop-off and proof of delivery workflow.", accent: "blue" },
  { key: "route-planning", title: "Route Planning", route: "/route-planning", group: "Dispatch", description: "Planned routes, stops, optimization signals and route exceptions.", accent: "purple" },
  { key: "vehicles", title: "Vehicles", route: "/vehicles", group: "Fleet", description: "Fleet registry, readiness, data quality, assignments and lifecycle risk.", accent: "blue" },
  { key: "drivers", title: "Drivers", route: "/drivers", group: "Fleet", description: "Driver readiness, safety score, assignments, HOS and coaching.", accent: "green" },
  { key: "assets", title: "Assets / Trailers / Equipment", route: "/assets", group: "Fleet", description: "Non-powered assets, trailers, equipment, availability and assignment state.", accent: "teal" },
  { key: "maintenance", title: "Maintenance", route: "/maintenance", group: "Maintenance", description: "Preventive maintenance, risk backlog and AI maintenance planning.", accent: "purple" },
  { key: "work-orders", title: "Work Orders", route: "/work-orders", group: "Maintenance", description: "Repair execution, priorities, estimated cost and technician workflow.", accent: "amber" },
  { key: "fuel-idling", title: "Fuel & Idling", route: "/fuel-idling", group: "Finance", description: "Fuel transactions, idling leakage, cost signals and coaching opportunities.", accent: "green" },
  { key: "safety", title: "Safety", route: "/safety", group: "Safety", description: "Safety events, risk severity, review queue and driver coaching.", accent: "red" },
  { key: "dashcam", title: "AI Dashcam / Incident Review", route: "/dashcam", group: "Safety", description: "AI dashcam incidents, evidence cards and coaching status.", accent: "purple" },
  { key: "coaching", title: "Driver Coaching", route: "/coaching", group: "Safety", description: "Coaching tasks, AI scripts, acknowledgements and effectiveness scoring.", accent: "green" },
  { key: "incidents", title: "Incidents", route: "/incidents", group: "Safety", description: "Incident register, statements, insurance reports and legal review placeholders.", accent: "red" },
  { key: "evidence-packages", title: "Evidence Packages", route: "/evidence-packages", group: "Safety", description: "Video, GPS, speed, DVIR, maintenance and document bundles for insurance/legal review.", accent: "blue" },
  { key: "compliance", title: "Compliance", route: "/compliance", group: "Compliance", description: "Documents, expirations, permit risk and compliance audit trail.", accent: "purple" },
  { key: "hos-eld", title: "HOS / ELD Framework", route: "/hos-eld", group: "Compliance", description: "Hours of service, cycle limits, ELD framework and violation signals.", accent: "amber" },
  { key: "dvir-inspections", title: "DVIR / Inspections", route: "/dvir-inspections", group: "Compliance", description: "Pre-trip/post-trip inspections, defects and vehicle readiness.", accent: "teal" },
  { key: "customer-portal", title: "Customer ETA Portal", route: "/customer-portal", group: "Dispatch", description: "Customer-facing ETA communications, status, proof and SLA transparency.", accent: "blue" },
  { key: "customers", title: "Clients / Customers", route: "/customers", group: "Platform", description: "Customer profiles, contacts, SLA tiers and service history.", accent: "blue" },
  { key: "contracts-rates", title: "Contracts / Rates", route: "/contracts-rates", group: "Finance", description: "Contracts, rate structures and pricing governance.", accent: "green" },
  { key: "carrier-management", title: "Carrier Management", route: "/carrier-management", group: "Dispatch", description: "Partner carriers, safety rating, rates and tendering readiness.", accent: "teal" },
  { key: "expenses", title: "Expenses", route: "/expenses", group: "Finance", description: "Operating expenses, review queue and exception management.", accent: "amber" },
  { key: "documents", title: "Documents", route: "/documents", group: "Platform", description: "Operational documents, proof, permits and lifecycle states.", accent: "blue" },
  { key: "reports-analytics", title: "Reports & Analytics", route: "/reports-analytics", group: "Intelligence", description: "Operational analytics, trend views and executive reporting.", accent: "purple" },
  { key: "sla-kpi", title: "SLA / KPI Center", route: "/sla-kpi", group: "Intelligence", description: "Customer SLA, KPI scorecards and target variance.", accent: "green" },
  { key: "predictive-margin", title: "Predictive Cost & Margin", route: "/predictive-margin", group: "Intelligence", description: "Cost leakage, margin forecast and predictive profitability signals.", accent: "purple" },
  { key: "cost-leakage", title: "ROI / Cost Leakage Intelligence", route: "/cost-leakage", group: "Intelligence", description: "Leakage categories, action queue, recoverable savings and cost recovery intelligence.", accent: "amber" },
  { key: "audit-logs", title: "Audit Logs", route: "/audit-logs", group: "Platform", description: "Immutable operating record for user, dispatch and AI actions.", accent: "amber" },
  { key: "ai-copilot", title: "OpsTrax AI Copilot", route: "/ai-copilot", group: "Intelligence", description: "AI workspace for cost, dispatch, maintenance, safety and executive prompts.", accent: "purple" },
  { key: "integrations", title: "Integrations", route: "/integrations", group: "Platform", description: "Telematics, ELD, finance, messaging and document integrations.", accent: "teal" },
  { key: "user-management", title: "User Management", route: "/user-management", group: "Platform", description: "Users, roles, permissions and RBAC metadata.", accent: "blue" },
  { key: "settings", title: "Settings", route: "/settings", group: "Platform", description: "Company preferences, simulation controls and platform settings.", accent: "teal" },
  { key: "billing", title: "Billing / Subscription", route: "/billing", group: "Platform", description: "Subscription plan, seats, billing status and account entitlements.", accent: "green" },
];

export const moduleIcons: Record<string, typeof Activity> = {
  "command-center": Gauge,
  "control-tower": Map,
  dispatch: RadioTower,
  jobs: PackageCheck,
  "route-planning": Route,
  vehicles: Truck,
  drivers: Users,
  assets: BriefcaseBusiness,
  maintenance: Wrench,
  "work-orders": ClipboardCheck,
  "fuel-idling": Fuel,
  safety: ShieldAlert,
  dashcam: Video,
  coaching: Users,
  incidents: ShieldAlert,
  "evidence-packages": FileText,
  compliance: FileCheck2,
  "hos-eld": Clock3,
  "dvir-inspections": ScrollText,
  "customer-portal": MapPinned,
  customers: Building2,
  "contracts-rates": Landmark,
  "carrier-management": Truck,
  expenses: WalletCards,
  documents: FileText,
  "reports-analytics": BarChart3,
  "sla-kpi": Activity,
  "predictive-margin": Zap,
  "cost-leakage": TrendingDown,
  "audit-logs": Siren,
  "ai-copilot": Bot,
  integrations: Settings,
  "user-management": UserCog,
  settings: Settings,
  billing: CreditCard,
};
