import {
  Activity,
  BarChart3,
  Bot,
  BrainCircuit,
  CalendarDays,
  ClipboardList,
  Leaf,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ClipboardCheck,
  Clock3,
  CreditCard,
  DollarSign,
  FileCheck2,
  FileText,
  Flag,
  Fuel,
  Gauge,
  Globe,
  HeartPulse,
  HeartHandshake,
  Info,
  Landmark,
  Map,
  MapPinned,
  Megaphone,
  PackageCheck,
  RadioTower,
  Receipt,
  Route,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Snowflake,
  TicketCheck,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  Video,
  WalletCards,
  Wrench,
  Zap,
} from "lucide-react";
import type { ModuleConfig } from "@/types";

/** Saudi Arabia plus the GCC states served by the Saudi/GCC compliance pack. */
export const GCC_COUNTRIES = ["SA", "AE", "QA", "KW", "BH", "OM"];

export const modules: ModuleConfig[] = [
  { key: "command-center",    title: "Dashboard",            route: "/command-center",    group: "Operations", description: "Live operating status — fleet readiness, dispatch exceptions, safety risk and cost leakage in one dashboard.", accent: "teal",   requiredPermission: "dashboard.view" },
  { key: "fleet-health",     title: "Fleet Health",         route: "/fleet-health",      group: "Operations", description: "Priority-ranked vehicles and drivers by risk — OOS status, critical defects, safety score and action queue.", accent: "red",    requiredPermission: "dashboard:view" },
  { key: "live-dashboard",   title: "Fleet Overview",       route: "/live-dashboard",    group: "Operations", description: "Live vehicle positions, operational status, HOS posture and fleet health at a glance.", accent: "blue",   requiredPermission: "dashboard.view" },
  { key: "map-view",         title: "Live Map",             route: "/map-view",          group: "Operations", description: "Real-time fleet positions, shipment routes, geofences and driver locations.", accent: "blue",   requiredPermission: "telemetry.live_state.read" },
  { key: "alerts",           title: "Alerts",               route: "/alerts",            group: "Operations", description: "Critical operating alerts across telematics, maintenance, customer SLA and safety.", accent: "red",    requiredPermission: "fleet.view" },
  { key: "active-shipments", title: "Active Shipments",     route: "/active-shipments",  group: "Operations", description: "Live shipment board with SLA, ETA, POD and invoice readiness.", accent: "teal",   requiredPermission: "dispatch.view" },
  { key: "geofences",         title: "Geofence Management",     route: "/geofences",         group: "Operations",        description: "Create, edit and monitor geofence zones — entry/exit events, vehicle alerts and boundary enforcement.", accent: "purple", requiredPermission: "map:view" },

  { key: "leads",              title: "Leads",              route: "/leads",              group: "CRM & Growth", description: "Prospect demand, service fit, source, owner and follow-up queue.", accent: "blue",   requiredPermission: "crm.view" },
  { key: "sales-pipeline",     title: "Sales Pipeline",     route: "/sales-pipeline",     group: "CRM & Growth", description: "Pipeline stage cockpit from lead through contract draft and win/loss.", accent: "green",  requiredPermission: "crm.view" },
  { key: "opportunities",      title: "Opportunities",      route: "/opportunities",      group: "CRM & Growth", description: "Opportunity value, load volume, probability, competitor and owner view.", accent: "teal",   requiredPermission: "crm.view" },
  { key: "campaigns",          title: "Campaigns",          route: "/campaigns",          group: "CRM & Growth", description: "Renewal, win-back, new lane, cross-sell and cold-chain promotion performance.", accent: "purple", requiredPermission: "campaigns.view" },
  { key: "account-health",     title: "Account Health",     route: "/account-health",     group: "CRM & Growth", description: "Health score, SLA, complaints, revenue trend, renewal risk and next action.", accent: "amber",  requiredPermission: "crm.view" },
  { key: "follow-ups",         title: "Follow-ups",         route: "/follow-ups",         group: "CRM & Growth", description: "Sales and account management follow-up discipline.", accent: "blue",   requiredPermission: "crm.view" },
  { key: "support-tickets",    title: "Support Tickets",    route: "/support-tickets",    group: "CRM & Growth", description: "Customer support issues connected to shipments, SLA timers and teams.", accent: "red",    requiredPermission: "crm.view" },
  { key: "renewals",           title: "Renewals",           route: "/renewals",           group: "CRM & Growth", description: "Contract renewal pipeline with revenue, margin, probability and risk.", accent: "green",  requiredPermission: "crm.view" },
  { key: "upsell-opportunities", title: "Upsell Opportunities", route: "/upsell-opportunities", group: "CRM & Growth", description: "Expansion plays from account and lane signals.", accent: "purple", requiredPermission: "crm.view" },

  { key: "customers",       title: "Customers",         route: "/customers",       group: "Commercial", description: "Customer profiles, shipment volume, revenue, health and active contracts.", accent: "blue",   requiredPermission: "crm.view" },
  { key: "contracts",       title: "Contracts",         route: "/contracts",       group: "Commercial", description: "Contract terms, SLA, billing, renewal and service governance.", accent: "green",  requiredPermission: "crm.view" },
  { key: "rate-cards",      title: "Rate Cards",        route: "/rate-cards",      group: "Commercial", description: "Lane pricing, vehicle pricing, fuel surcharge and effective periods.", accent: "teal",   requiredPermission: "crm.view" },
  { key: "price-simulation",title: "Price Simulation",  route: "/price-simulation",group: "Commercial", description: "Quote calculator for lane, cargo, vehicle, temperature and margin.", accent: "purple", requiredPermission: "crm.view" },
  { key: "quotations",      title: "Quotations",        route: "/quotations",      group: "Commercial", description: "Quote lifecycle from draft to sent, accepted and converted booking.", accent: "amber",  requiredPermission: "crm.view" },

  { key: "load-bookings",      title: "Load Bookings",      route: "/load-bookings",      group: "Transport Operations", description: "Customer booking workflow from quoted load to dispatch-ready demand.", accent: "blue",   requiredPermission: "orders.view" },
  { key: "shipments",          title: "Shipments",          route: "/shipments",          group: "Transport Operations", description: "Execution register for active freight, status, ETA, POD and invoice.", accent: "teal",   requiredPermission: "shipments.view" },
  { key: "dispatch-board",     title: "Dispatch Board",     route: "/dispatch",           group: "Transport Operations", description: "Driver and vehicle assignment cockpit with match scores and exception radar.", accent: "green",  requiredPermission: "dispatch.view" },
  { key: "jobs",               title: "Jobs",               route: "/jobs",               group: "Transport Operations", description: "Job register — delivery, collection, transfer, and job status with driver and vehicle linkage.", accent: "teal",   requiredPermission: "dispatch.view" },
  { key: "trips",              title: "Trips",              route: "/trips",              group: "Transport Operations", description: "Trip register with route compliance, breadcrumbs, driver/vehicle linkage and dispatch actions.", accent: "blue",   requiredPermission: "dispatch.view" },
  { key: "route-plans",        title: "Route Plans",        route: "/route-plans",        group: "Transport Operations", description: "Route library, lane risk, distance, duration, toll and vehicle fit.", accent: "purple", requiredPermission: "dispatch.view" },
  { key: "proof-of-delivery",  title: "Proof of Delivery",  route: "/proof-of-delivery",  group: "Transport Operations", description: "POD capture, GPS verification, photos, signature and invoice readiness.", accent: "green",  requiredPermission: "shipments:view" },
  { key: "last-mile-delivery", title: "Last Mile Delivery", route: "/last-mile-delivery", group: "Transport Operations", description: "Final-mile runs with ETA, proof, stop status and customer experience.", accent: "blue",   requiredPermission: "dispatch.view" },
  { key: "operations-proof-center", title: "Operational Proof Center", route: "/operations/proof-center", group: "Transport Operations", description: "Execution summary, proof workflow, access controls, handover, billing confidence and mobile-readiness preview.", accent: "teal", requiredPermission: "operations.execution_summary.read" },
  { key: "logistics-workspace", title: "Logistics Workspace", route: "/logistics-workspace", group: "Transport Operations", description: "Last-mile command: dispatch orders, delivery routes and live stop progression with deliver/attempt/reschedule actions.", accent: "blue", requiredPermission: "dispatch:view" },

  { key: "fleet-utilization", title: "Fleet Utilization", route: "/fleet-utilization", group: "Fleet", description: "Vehicle utilization %, idle time, fuel efficiency, active hours and per-vehicle productivity analytics.", accent: "teal", requiredPermission: "fleet:view" },
  { key: "fleet-workspace", title: "Fleet TMS Workspace", route: "/fleet-workspace", group: "Fleet", description: "Shipment lifecycle, POD verification, public tracking links, vehicles, tracking, maintenance and fuel in one operations cockpit.", accent: "teal", requiredPermission: "fleet:view" },
  { key: "fleet-cold-chain", title: "Cold Chain Monitor", route: "/fleet-cold-chain", group: "Fleet", description: "Temperature zones, sensor devices, live readings, breach alerts and per-shipment cold-chain compliance reports.", accent: "blue", requiredPermission: "fleet:view" },
  { key: "fleet-assets", title: "Returnable Assets", route: "/fleet-assets", group: "Fleet", description: "Pallets, roll cages and crates with check-in/out, assignments, barcode/RFID scans and asset event history.", accent: "green", requiredPermission: "fleet:view" },
  { key: "fleet-saudi-readiness", title: "Saudi Readiness", route: "/fleet-saudi-readiness", group: "Fleet", description: "Saudi/GCC region reference, ZATCA VAT invoice-readiness and compliance document expiry tracking. Visible only to tenants whose operating region is Saudi/GCC.", accent: "amber", requiredPermission: "fleet:view", requiredCountries: GCC_COUNTRIES },
  { key: "fleet-compliance", title: "Fleet Compliance", route: "/fleet-compliance", group: "Fleet", description: "Market-pack readiness — Canada/NA driver qualification, DVIR, IFTA & HOS/ELD foundation; Saudi/GCC transport documents, VAT & Hijri expiry.", accent: "blue", requiredPermission: "compliance:view" },
  { key: "vehicles",    title: "Vehicles",    route: "/vehicles",    group: "Fleet", description: "Fleet registry, age, readiness, documents, device visibility and lifecycle planning.", accent: "blue",   requiredPermission: "vehicles:view" },
  { key: "drivers",     title: "Drivers",     route: "/drivers",     group: "Fleet", description: "Driver availability, HOS, safety, documents, assignment and coaching state.", accent: "green",  requiredPermission: "drivers.view" },
  { key: "owners",      title: "Owners",      route: "/owners",      group: "Fleet", description: "Owner-operator and asset ownership management.", accent: "teal",   requiredPermission: "fleet.view" },
  { key: "assignments", title: "Assignments", route: "/assignments", group: "Fleet", description: "Driver, vehicle, device and asset assignment history.", accent: "purple", requiredPermission: "fleet.view" },
  { key: "documents",   title: "Documents",   route: "/documents",   group: "Fleet", description: "Vehicle, driver, contract, POD, invoice and compliance document vault.", accent: "blue",   requiredPermission: "fleet.view" },

  { key: "iot-devices",    title: "Device Health", route: "/iot-devices", group: "Telematics & IoT", description: "Fleet device control for GPS, ELD, OBD, dashcam, sensor, firmware, diagnostics, and install posture.", accent: "blue", requiredPermission: "telemetry.devices.read" },
  { key: "gps-tracking",   title: "GPS Tracking",   route: "/gps-tracking",   group: "Telematics & IoT", description: "GPS position, history, geofence and location quality signals.", accent: "teal",   requiredPermission: "telematics:gps:view" },
  { key: "obd-j1939",      title: "OBD / J1939",    route: "/obd-j1939",      group: "Telematics & IoT", description: "Engine diagnostics, fault codes, odometer, fuel and vehicle health telemetry.", accent: "amber",  requiredPermission: "telematics:diagnostics:view" },
  { key: "cold-chain",     title: "Cold Chain",     route: "/cold-chain",     group: "Telematics & IoT", description: "Temperature, set point, humidity, door status and breach compliance.", accent: "blue",   requiredPermission: "telematics:sensors:view" },
  { key: "dashcam",        title: "Dashcam Events", route: "/dashcam",        group: "Telematics & IoT", description: "Dashcam events, review workflow, clips and evidence creation.", accent: "purple", requiredPermission: "dashcam.view" },
  { key: "sensor-health",  title: "Sensor Health",  route: "/sensor-health",  group: "Telematics & IoT", description: "Offline devices, weak signal, firmware issues, no heartbeat and tamper watch.", accent: "red",    requiredPermission: "telematics:sensors:view" },

  { key: "driver-scorecards", title: "Driver Scorecards",  route: "/driver-scorecards", group: "Safety & Compliance", description: "Fleet-wide safety scoring — harsh braking, acceleration, speeding, events and coaching workflow.", accent: "teal",   requiredPermission: "safety.view" },
  { key: "incidents",         title: "Incidents",          route: "/incidents",         group: "Safety & Compliance", description: "Incident register, statements, evidence, insurance and legal workflow.", accent: "red",    requiredPermission: "safety.view" },
  { key: "coaching",          title: "Driver Coaching",    route: "/coaching",          group: "Safety & Compliance", description: "Coaching tasks, acknowledgements and safety score impact.", accent: "green",  requiredPermission: "safety.view" },
  { key: "dvir-inspections",  title: "DVIR",               route: "/dvir-inspections",  group: "Safety & Compliance", description: "Driver vehicle inspection reports, defects, signatures and mechanic review.", accent: "teal",   requiredPermission: "maintenance.view" },
  { key: "hos-eld",           title: "HOS / ELD",          route: "/hos-eld",           group: "Safety & Compliance", description: "Hours of service, ELD sync, violation risk and driver duty status.", accent: "amber",  requiredPermission: "compliance.view" },
  { key: "traffic-violations",title: "Traffic Violations", route: "/traffic-violations",group: "Safety & Compliance", description: "Speeding, phone use, seatbelt, red-light and route violation watch.", accent: "red",    requiredPermission: "safety.view" },
  { key: "evidence-packages", title: "Evidence Packages",  route: "/evidence-packages", group: "Safety & Compliance", description: "Video, GPS, speed, DVIR, documents and chain-of-custody bundles.", accent: "blue",   requiredPermission: "safety.view" },

  { key: "work-orders",            title: "Work Orders",           route: "/work-orders",            group: "Maintenance", description: "Repair execution, priority, vendor, labor, parts and cost approval.", accent: "amber",  requiredPermission: "maintenance.view" },
  { key: "service-history",        title: "Service History",       route: "/service-history",        group: "Maintenance", description: "Completed service events, cost, downtime, provider and notes.", accent: "blue",   requiredPermission: "maintenance.view" },
  { key: "downtime",               title: "Downtime",              route: "/downtime",               group: "Maintenance", description: "Vehicle downtime events, duration, cause and revenue impact.", accent: "red",    requiredPermission: "maintenance.view" },
  { key: "preventive-maintenance", title: "Preventive Maintenance",route: "/preventive-maintenance", group: "Maintenance", description: "PM schedules, service due, odometer triggers and risk forecasting.", accent: "green",  requiredPermission: "maintenance.view" },

  { key: "fuel-idling",    title: "Fuel Transactions", route: "/fuel-idling",    group: "Financials", description: "Fuel purchases, cards, stations, odometer and anomaly flags.", accent: "green",  requiredPermission: "fuel.view" },
  { key: "expenses",       title: "Expenses",          route: "/expenses",       group: "Financials", description: "Operating expenses, approvals, tax, receipts and budget variance.", accent: "amber",  requiredPermission: "finance.view" },
  { key: "invoices",       title: "Invoices",          route: "/invoices",       group: "Financials", description: "Invoice lifecycle, aging, payment state and shipment linkage.", accent: "blue",   requiredPermission: "finance.view" },
  { key: "ar-aging",       title: "AR Aging",          route: "/ar-aging",       group: "Financials", description: "Outstanding receivables bucketed by days past due, per customer.", accent: "amber",  requiredPermission: "finance.view" },
  { key: "payments",       title: "Payments",          route: "/payments",       group: "Financials", description: "Collections, payment methods, unapplied cash and customer payment health.", accent: "green",  requiredPermission: "finance.view" },
  { key: "profitability",  title: "Profitability",     route: "/profitability",  group: "Financials", description: "Revenue by customer, route and shipment; cost by vehicle; margin leakage.", accent: "purple", requiredPermission: "finance.view" },

  { key: "user-management", title: "Users & Roles",  route: "/user-management", group: "Governance", description: "Users, tenants, roles, permissions and access posture.", accent: "blue",   requiredPermission: "users.manage" },
  { key: "audit-logs",      title: "Audit Logs",     route: "/audit-logs",      group: "Governance", description: "Immutable activity record across users, dispatch, safety, operations and billing.", accent: "amber",  requiredPermission: "reports.manage" },
  { key: "integrations",    title: "Integrations",   route: "/integrations",    group: "Governance", description: "Live connector hub for ERP, accounting, telematics, fuel cards, maps, messaging, WMS and compliance integrations.", accent: "teal",   requiredPermission: "telematics:providers:manage" },

  { key: "carbon-tracking",   title: "Carbon Tracking",     route: "/carbon-tracking",   group: "Intelligence",        description: "Fleet CO₂ emissions, sustainability KPIs, reduction targets and carbon intensity per shipment.", accent: "green",  requiredPermission: "reports.view" },
  { key: "digital-forms",    title: "Digital Forms",       route: "/digital-forms",     group: "Safety & Compliance", description: "Pre-trip, post-trip, incident, delivery and compliance digital form templates and submissions.", accent: "blue",   requiredPermission: "safety.view" },
  { key: "alert-rules",      title: "Alert Rules",         route: "/alert-rules",       group: "Governance",          description: "Configure speed, idling, geofence, HOS, maintenance and safety alert thresholds with notification channels.", accent: "red",    requiredPermission: "alerts.view" },
  { key: "driver-messaging", title: "Driver Messaging",    route: "/driver-messaging",  group: "Transport Operations", description: "Send dispatch instructions, safety alerts and broadcast announcements to drivers via in-app and SMS.", accent: "teal",  requiredPermission: "dispatch.view" },
  { key: "workforce", title: "Workforce Management", route: "/workforce", group: "Transport Operations", description: "Driver shift scheduling calendar, availability tracking, HOS compliance indicators and automated roster optimisation.", accent: "teal", requiredPermission: "dispatch.view" },

  { key: "feature-flags",        title: "Feature Flags",       route: "/feature-flags",        group: "Governance",   description: "Kill switches and gradual rollouts. Turning a flag off blocks its API (403) and hides it in the UI — no deploy.", accent: "purple", requiredPermission: "users.manage" },
  { key: "ai-copilot",           title: "Operations Copilot",  route: "/ai-copilot",           group: "Intelligence", description: "Operational query workspace for cost, dispatch, maintenance, safety and executive analysis.", accent: "purple", requiredPermission: "reports.view" },
  { key: "predictive-analytics", title: "Fleet Intelligence",  route: "/predictive-analytics",  group: "Intelligence", description: "Maintenance failure predictions, driver safety risk scores, and SLA breach probability.", accent: "purple", requiredPermission: "reports.view" },
  { key: "control-tower",     title: "Control Tower",       route: "/control-tower",     group: "Intelligence", description: "Connected live map and control tower.", accent: "blue",   requiredPermission: "dashboard.view" },
  { key: "reports-analytics", title: "Reports & Analytics", route: "/reports-analytics", group: "Intelligence", description: "Operational analytics, trend views and executive reporting.", accent: "purple", requiredPermission: "reports.view" },
  { key: "about",             title: "About OpsTrax",       route: "/about",             group: "Governance",   description: "Platform overview, system health and support.", accent: "purple", requiredPermission: "settings.view" },
];

export const moduleIcons: Record<string, typeof Activity> = {
  "command-center": Gauge,
  "fleet-health": ShieldCheck,
  "live-dashboard": BarChart3,
  "active-shipments": PackageCheck,
  alerts: Siren,
  "map-view": Map,
  leads: Users,
  "sales-pipeline": TrendingUp,
  opportunities: BriefcaseBusiness,
  campaigns: Megaphone,
  "account-health": HeartPulse,
  "follow-ups": Clock3,
  "support-tickets": TicketCheck,
  renewals: ScrollText,
  "upsell-opportunities": Zap,
  customers: Building2,
  contracts: Landmark,
  "rate-cards": Receipt,
  "price-simulation": Calculator,
  quotations: FileText,
  "load-bookings": ClipboardCheck,
  shipments: PackageCheck,
  "dispatch-board": RadioTower,
  "route-plans": Route,
  trips: Route,
  "proof-of-delivery": FileCheck2,
  "last-mile-delivery": MapPinned,
  "operations-proof-center": ClipboardCheck,
  "logistics-workspace": Map,
  vehicles: Truck,
  drivers: Users,
  owners: UserCog,
  assignments: Activity,
  documents: FileText,
  "iot-devices": RadioTower,
  "gps-tracking": MapPinned,
  "obd-j1939": Gauge,
  "cold-chain": Snowflake,
  dashcam: Video,
  "sensor-health": Activity,
  incidents: ShieldAlert,
  coaching: Users,
  "dvir-inspections": ScrollText,
  "hos-eld": Clock3,
  "traffic-violations": Flag,
  "evidence-packages": FileText,
  "work-orders": ClipboardCheck,
  "service-history": Wrench,
  downtime: TrendingDown,
  "preventive-maintenance": Wrench,
  "fleet-utilization": BarChart3,
  "fleet-workspace": Truck,
  "fleet-cold-chain": Snowflake,
  "fleet-assets": PackageCheck,
  "fleet-saudi-readiness": ShieldCheck,
  "fleet-compliance": ShieldCheck,
  "driver-scorecards": ShieldCheck,
  "fuel-idling": Fuel,
  expenses: WalletCards,
  invoices: DollarSign,
  "ar-aging": DollarSign,
  payments: CreditCard,
  profitability: BarChart3,
  "user-management": UserCog,
  "audit-logs": Siren,
  "feature-flags": Settings,
  integrations: Settings,
  "carbon-tracking": Leaf,
  "digital-forms": ClipboardList,
  "alert-rules": Siren,
  "driver-messaging": Megaphone,
  workforce: CalendarDays,
  "ai-copilot": Bot,
  "predictive-analytics": BrainCircuit,
  "control-tower": Map,
  "reports-analytics": BarChart3,
  about: Info,
  compliance: FileCheck2,
  maintenance: Wrench,
  safety: ShieldAlert,
  jobs: PackageCheck,
  dispatch: RadioTower,
  assets: BriefcaseBusiness,
  settings: Settings,
  billing: CreditCard,
  companies: Globe,
};
