import {
  Activity,
  BarChart3,
  Bot,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ClipboardCheck,
  Clock3,
  CreditCard,
  DollarSign,
  FileCheck2,
  FileText,
  Flag,
  Fuel,
  Gauge,
  Globe,
  HeartPulse,
  Info,
  Landmark,
  Map,
  MapPinned,
  Megaphone,
  PackageCheck,
  RadioTower,
  Receipt,
  Route,
  ScrollText,
  Settings,
  ShieldAlert,
  Siren,
  Snowflake,
  TicketCheck,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  Video,
  WalletCards,
  Wrench,
  Zap,
} from "lucide-react";
import type { ModuleConfig } from "@/types";

export const modules: ModuleConfig[] = [
  { key: "live-dashboard",    title: "Live Dashboard",          route: "/live-dashboard",    group: "Control Tower",        description: "Executive transport cockpit for shipments, fleet, alerts, ETA, revenue, cost and margin.", accent: "blue",   requiredPermission: "dashboard:view" },
  { key: "active-shipments",  title: "Active Shipments",        route: "/active-shipments",  group: "Control Tower",        description: "Live shipment board with SLA, ETA, POD and invoice readiness.", accent: "teal",   requiredPermission: "dispatch:view" },
  { key: "alerts",            title: "Alerts",                  route: "/alerts",            group: "Control Tower",        description: "Critical operating alerts across telematics, maintenance, customer SLA and safety.", accent: "red",    requiredPermission: "fleet:view" },
  { key: "map-view",          title: "Fleet 360 Command View",  route: "/map-view",          group: "Control Tower",        description: "Map-first command cockpit for fleet, shipments, drivers, devices, safety, compliance and margin risk.", accent: "blue",   requiredPermission: "map:view" },

  { key: "leads",              title: "Leads",              route: "/leads",              group: "CRM & Growth", description: "Prospect demand, service fit, source, owner and follow-up queue.", accent: "blue",   requiredPermission: "crm:view" },
  { key: "sales-pipeline",     title: "Sales Pipeline",     route: "/sales-pipeline",     group: "CRM & Growth", description: "Pipeline stage cockpit from lead through contract draft and win/loss.", accent: "green",  requiredPermission: "crm:view" },
  { key: "opportunities",      title: "Opportunities",      route: "/opportunities",      group: "CRM & Growth", description: "Opportunity value, load volume, probability, competitor and owner view.", accent: "teal",   requiredPermission: "crm:view" },
  { key: "campaigns",          title: "Campaigns",          route: "/campaigns",          group: "CRM & Growth", description: "Renewal, win-back, new lane, cross-sell and cold-chain promotion performance.", accent: "purple", requiredPermission: "crm:view" },
  { key: "account-health",     title: "Account Health",     route: "/account-health",     group: "CRM & Growth", description: "Health score, SLA, complaints, revenue trend, renewal risk and next action.", accent: "amber",  requiredPermission: "crm:view" },
  { key: "follow-ups",         title: "Follow-ups",         route: "/follow-ups",         group: "CRM & Growth", description: "Sales and account management follow-up discipline.", accent: "blue",   requiredPermission: "crm:view" },
  { key: "support-tickets",    title: "Support Tickets",    route: "/support-tickets",    group: "CRM & Growth", description: "Customer support issues connected to shipments, SLA timers and teams.", accent: "red",    requiredPermission: "crm:view" },
  { key: "renewals",           title: "Renewals",           route: "/renewals",           group: "CRM & Growth", description: "Contract renewal pipeline with revenue, margin, probability and risk.", accent: "green",  requiredPermission: "crm:view" },
  { key: "upsell-opportunities", title: "Upsell Opportunities", route: "/upsell-opportunities", group: "CRM & Growth", description: "AI-assisted expansion plays from account and lane signals.", accent: "purple", requiredPermission: "crm:view" },

  { key: "customers",       title: "Customers",         route: "/customers",       group: "Commercial", description: "Customer profiles, shipment volume, revenue, health and active contracts.", accent: "blue",   requiredPermission: "customers:view" },
  { key: "contracts",       title: "Contracts",         route: "/contracts",       group: "Commercial", description: "Contract terms, SLA, billing, renewal and service governance.", accent: "green",  requiredPermission: "customers:view" },
  { key: "rate-cards",      title: "Rate Cards",        route: "/rate-cards",      group: "Commercial", description: "Lane pricing, vehicle pricing, fuel surcharge and effective periods.", accent: "teal",   requiredPermission: "customers:view" },
  { key: "price-simulation",title: "Price Simulation",  route: "/price-simulation",group: "Commercial", description: "Quote calculator for lane, cargo, vehicle, temperature and margin.", accent: "purple", requiredPermission: "customers:view" },
  { key: "quotations",      title: "Quotations",        route: "/quotations",      group: "Commercial", description: "Quote lifecycle from draft to sent, accepted and converted booking.", accent: "amber",  requiredPermission: "customers:view" },

  { key: "load-bookings",      title: "Load Bookings",      route: "/load-bookings",      group: "Transport Operations", description: "Customer booking workflow from quoted load to dispatch-ready demand.", accent: "blue",   requiredPermission: "dispatch:view" },
  { key: "shipments",          title: "Shipments",          route: "/shipments",          group: "Transport Operations", description: "Execution register for active freight, status, ETA, POD and invoice.", accent: "teal",   requiredPermission: "dispatch:view" },
  { key: "dispatch-board",     title: "Dispatch Board",     route: "/dispatch",           group: "Transport Operations", description: "Driver and vehicle assignment with AI fit scoring.", accent: "green",  requiredPermission: "dispatch:view" },
  { key: "route-plans",        title: "Route Plans",        route: "/route-plans",        group: "Transport Operations", description: "Route library, lane risk, distance, duration, toll and vehicle fit.", accent: "purple", requiredPermission: "dispatch:view" },
  { key: "proof-of-delivery",  title: "Proof of Delivery",  route: "/proof-of-delivery",  group: "Transport Operations", description: "POD capture, GPS verification, photos, signature and invoice readiness.", accent: "green",  requiredPermission: "dispatch:view" },
  { key: "last-mile-delivery", title: "Last Mile Delivery", route: "/last-mile-delivery", group: "Transport Operations", description: "Final-mile runs with ETA, proof, stop status and customer experience.", accent: "blue",   requiredPermission: "dispatch:view" },

  { key: "vehicles",    title: "Vehicles",    route: "/vehicles",    group: "Fleet", description: "Fleet registry, age, readiness, documents, device visibility and lifecycle planning.", accent: "blue",   requiredPermission: "fleet:view" },
  { key: "drivers",     title: "Drivers",     route: "/drivers",     group: "Fleet", description: "Driver availability, HOS, safety, documents, assignment and coaching state.", accent: "green",  requiredPermission: "fleet:view" },
  { key: "owners",      title: "Owners",      route: "/owners",      group: "Fleet", description: "Owner-operator and asset ownership management.", accent: "teal",   requiredPermission: "fleet:view" },
  { key: "assignments", title: "Assignments", route: "/assignments", group: "Fleet", description: "Driver, vehicle, device and asset assignment history.", accent: "purple", requiredPermission: "fleet:view" },
  { key: "documents",   title: "Documents",   route: "/documents",   group: "Fleet", description: "Vehicle, driver, contract, POD, invoice and compliance document vault.", accent: "blue",   requiredPermission: "fleet:view" },

  { key: "iot-devices",    title: "IoT Devices",    route: "/iot-devices",    group: "Telematics & IoT", description: "Devices, IMEI, SIM, firmware, heartbeat, battery, signal and health.", accent: "blue",   requiredPermission: "telematics:view" },
  { key: "gps-tracking",   title: "GPS Tracking",   route: "/gps-tracking",   group: "Telematics & IoT", description: "GPS position, history, geofence and location quality signals.", accent: "teal",   requiredPermission: "telematics:view" },
  { key: "obd-j1939",      title: "OBD / J1939",    route: "/obd-j1939",      group: "Telematics & IoT", description: "Engine diagnostics, fault codes, odometer, fuel and vehicle health telemetry.", accent: "amber",  requiredPermission: "telematics:view" },
  { key: "cold-chain",     title: "Cold Chain",     route: "/cold-chain",     group: "Telematics & IoT", description: "Temperature, set point, humidity, door status and breach compliance.", accent: "blue",   requiredPermission: "telematics:view" },
  { key: "dashcam",        title: "AI Dashcams",    route: "/dashcam",        group: "Telematics & IoT", description: "AI dashcam events, review workflow, clips and evidence creation.", accent: "purple", requiredPermission: "safety:view" },
  { key: "sensor-health",  title: "Sensor Health",  route: "/sensor-health",  group: "Telematics & IoT", description: "Offline devices, weak signal, firmware issues, no heartbeat and tamper watch.", accent: "red",    requiredPermission: "telematics:view" },

  { key: "incidents",         title: "Incidents",          route: "/incidents",         group: "Safety & Compliance", description: "Incident register, statements, evidence, insurance and legal workflow.", accent: "red",    requiredPermission: "safety:view" },
  { key: "coaching",          title: "Driver Coaching",    route: "/coaching",          group: "Safety & Compliance", description: "Coaching tasks, AI scripts, acknowledgements and score impact.", accent: "green",  requiredPermission: "safety:view" },
  { key: "dvir-inspections",  title: "DVIR",               route: "/dvir-inspections",  group: "Safety & Compliance", description: "Driver vehicle inspection reports, defects, signatures and mechanic review.", accent: "teal",   requiredPermission: "maintenance:view" },
  { key: "hos-eld",           title: "HOS / ELD",          route: "/hos-eld",           group: "Safety & Compliance", description: "Hours of service, ELD sync, violation risk and driver duty status.", accent: "amber",  requiredPermission: "compliance:view" },
  { key: "traffic-violations",title: "Traffic Violations", route: "/traffic-violations",group: "Safety & Compliance", description: "Speeding, phone use, seatbelt, red-light and route violation watch.", accent: "red",    requiredPermission: "safety:view" },
  { key: "evidence-packages", title: "Evidence Packages",  route: "/evidence-packages", group: "Safety & Compliance", description: "Video, GPS, speed, DVIR, documents and chain-of-custody bundles.", accent: "blue",   requiredPermission: "safety:view" },

  { key: "work-orders",            title: "Work Orders",           route: "/work-orders",            group: "Maintenance", description: "Repair execution, priority, vendor, labor, parts and cost approval.", accent: "amber",  requiredPermission: "maintenance:view" },
  { key: "service-history",        title: "Service History",       route: "/service-history",        group: "Maintenance", description: "Completed service events, cost, downtime, provider and notes.", accent: "blue",   requiredPermission: "maintenance:view" },
  { key: "downtime",               title: "Downtime",              route: "/downtime",               group: "Maintenance", description: "Vehicle downtime events, duration, cause and revenue impact.", accent: "red",    requiredPermission: "maintenance:view" },
  { key: "preventive-maintenance", title: "Preventive Maintenance",route: "/preventive-maintenance", group: "Maintenance", description: "PM schedules, service due, odometer triggers and risk forecasting.", accent: "green",  requiredPermission: "maintenance:view" },

  { key: "fuel-idling",    title: "Fuel Transactions", route: "/fuel-idling",    group: "Financials", description: "Fuel purchases, cards, stations, odometer and anomaly flags.", accent: "green",  requiredPermission: "finance:view" },
  { key: "expenses",       title: "Expenses",          route: "/expenses",       group: "Financials", description: "Operating expenses, approvals, tax, receipts and budget variance.", accent: "amber",  requiredPermission: "finance:view" },
  { key: "invoices",       title: "Invoices",          route: "/invoices",       group: "Financials", description: "Invoice lifecycle, aging, payment state and shipment linkage.", accent: "blue",   requiredPermission: "finance:view" },
  { key: "payments",       title: "Payments",          route: "/payments",       group: "Financials", description: "Collections, payment methods, unapplied cash and customer payment health.", accent: "green",  requiredPermission: "finance:view" },
  { key: "profitability",  title: "Profitability",     route: "/profitability",  group: "Financials", description: "Revenue by customer, route and shipment; cost by vehicle; margin leakage.", accent: "purple", requiredPermission: "finance:view" },

  { key: "user-management", title: "Users & Roles",  route: "/user-management", group: "Governance", description: "Users, tenants, roles, permissions and access posture.", accent: "blue",   requiredPermission: "governance:manage" },
  { key: "audit-logs",      title: "Audit Logs",     route: "/audit-logs",      group: "Governance", description: "Immutable activity record across users, dispatch, safety, AI and billing.", accent: "amber",  requiredPermission: "audit:view" },
  { key: "feature-flags",   title: "Feature Flags",  route: "/feature-flags",   group: "Governance", description: "Tenant feature rollout, beta controls and operational toggles.", accent: "purple", requiredPermission: "governance:manage" },
  { key: "integrations",    title: "Integrations",   route: "/integrations",    group: "Governance", description: "ERP, WMS, accounting, telematics, fuel card, messaging and payment integrations.", accent: "teal",   requiredPermission: "governance:manage" },

  { key: "ai-copilot",        title: "OpsTrax AI Copilot",   route: "/ai-copilot",        group: "Intelligence", description: "AI workspace for cost, dispatch, maintenance, safety and executive prompts.", accent: "purple", requiredPermission: "intelligence:view" },
  { key: "command-center",    title: "Command Center",       route: "/command-center",    group: "Intelligence", description: "Existing executive command center and operational AI brief.", accent: "teal",   requiredPermission: "dashboard:view" },
  { key: "control-tower",     title: "Legacy Control Tower", route: "/control-tower",     group: "Intelligence", description: "Existing connected live map/control tower implementation.", accent: "blue",   requiredPermission: "dashboard:view" },
  { key: "reports-analytics", title: "Reports & Analytics",  route: "/reports-analytics", group: "Intelligence", description: "Operational analytics, trend views and executive reporting.", accent: "purple", requiredPermission: "intelligence:view" },
  { key: "about",             title: "About OpsTrax",        route: "/about",             group: "Governance",   description: "Platform overview, Kode Kinetics developer info and system health.", accent: "purple" },
];

export const moduleIcons: Record<string, typeof Activity> = {
  "live-dashboard": Gauge,
  "active-shipments": PackageCheck,
  alerts: Siren,
  "map-view": Map,
  leads: Users,
  "sales-pipeline": TrendingUp,
  opportunities: BriefcaseBusiness,
  campaigns: Megaphone,
  "account-health": HeartPulse,
  "follow-ups": Clock3,
  "support-tickets": TicketCheck,
  renewals: ScrollText,
  "upsell-opportunities": Zap,
  customers: Building2,
  contracts: Landmark,
  "rate-cards": Receipt,
  "price-simulation": Calculator,
  quotations: FileText,
  "load-bookings": ClipboardCheck,
  shipments: PackageCheck,
  "dispatch-board": RadioTower,
  "route-plans": Route,
  "proof-of-delivery": FileCheck2,
  "last-mile-delivery": MapPinned,
  vehicles: Truck,
  drivers: Users,
  owners: UserCog,
  assignments: Activity,
  documents: FileText,
  "iot-devices": RadioTower,
  "gps-tracking": MapPinned,
  "obd-j1939": Gauge,
  "cold-chain": Snowflake,
  dashcam: Video,
  "sensor-health": Activity,
  incidents: ShieldAlert,
  coaching: Users,
  "dvir-inspections": ScrollText,
  "hos-eld": Clock3,
  "traffic-violations": Flag,
  "evidence-packages": FileText,
  "work-orders": ClipboardCheck,
  "service-history": Wrench,
  downtime: TrendingDown,
  "preventive-maintenance": Wrench,
  "fuel-idling": Fuel,
  expenses: WalletCards,
  invoices: DollarSign,
  payments: CreditCard,
  profitability: BarChart3,
  "user-management": UserCog,
  "audit-logs": Siren,
  "feature-flags": Settings,
  integrations: Settings,
  "ai-copilot": Bot,
  "command-center": Gauge,
  "control-tower": Map,
  "reports-analytics": BarChart3,
  about: Info,
  compliance: FileCheck2,
  maintenance: Wrench,
  safety: ShieldAlert,
  jobs: PackageCheck,
  dispatch: RadioTower,
  assets: BriefcaseBusiness,
  settings: Settings,
  billing: CreditCard,
  companies: Globe,
};
