using Opstrax.Api.Foundation;

namespace Opstrax.Api.Services;

// GL derive-beside handler: every issued invoice auto-posts to the general ledger
// (Dr Accounts Receivable / Cr Freight Revenue / Cr Tax Payable) so the trial balance is generated by
// the business events themselves rather than reconciled after the fact. Runs in fan-out alongside
// InvoiceIssuedRecognitionHandler on the same invoice.issued event.
// Idempotent: PostInvoiceAsync early-returns the existing entry via UNIQUE(company_id, source_type,
// source_ref), so at-least-once outbox delivery yields exactly one journal entry. Fail-closed: an
// imbalanced invoice (total != subtotal + tax_total) or missing invoice row throws -> the outbox
// retries then dead-letters, surfacing the bad data instead of corrupting the ledger. A malformed
// aggregateId also throws (visible) rather than silently no-op'ing — this is a money path.
public sealed class InvoiceIssuedGeneralLedgerHandler(GeneralLedgerService gl) : IOutboxMessageHandler
{
    public string EventType => "invoice.issued";

    public async Task HandleAsync(OutboxMessageRecord message, CancellationToken ct = default)
    {
        if (!long.TryParse(message.TenantId, out var companyId)) return;
        if (!Guid.TryParse(message.AggregateId, out _))
            throw new InvalidOperationException($"invoice.issued aggregateId is not an invoice UUID: '{message.AggregateId}'");
        await gl.PostInvoiceAsync(companyId, message.AggregateId, ct);
    }
}
