-- Stage 58 -- non-forgeable, transaction-bound tenant authorization
--
-- A PostgreSQL custom GUC is not an authorization boundary: any connected role can
-- set app.current_tenant_id/app.platform_admin.  This terminal reconciliation
-- replaces every GUC-trusting tenant policy with two role-targeted policies:
--   * tenant_ticket_app      TO opstrax_app, derives the tenant only from a signed
--                            capability bound to PID + transaction + expiry; and
--   * system_control_plane   TO opstrax_system, the separately credentialed,
--                            restricted system lane.
--
-- No password is stored here. Operators provision independent strong passwords for
-- opstrax_app and opstrax_system out of band. The HMAC key is generated by this
-- owner migration and remains readable only by SECURITY DEFINER functions.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $roles$
DECLARE rec record;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='opstrax_app') THEN
    RAISE EXCEPTION 'Stage 58 requires opstrax_app; apply Stage 20 first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='opstrax_system') THEN
    CREATE ROLE opstrax_system LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  END IF;
  -- Managed Postgres (Neon/RDS) never grants superuser, and naming the SUPERUSER /
  -- BYPASSRLS / REPLICATION attributes in ALTER ROLE requires it — even when the values
  -- already match, which would fail here with "permission denied to alter role". Only
  -- issue the ALTER for a role that actually deviates from the target shape; the
  -- verification block below still fails loudly if a role is wrong and uncorrectable.
  FOR rec IN
    SELECT rolname FROM pg_roles
    WHERE rolname IN ('opstrax_app','opstrax_system')
      AND (NOT rolcanlogin OR rolsuper OR rolbypassrls OR rolcreatedb
           OR rolcreaterole OR rolinherit OR rolreplication)
  LOOP
    EXECUTE format('ALTER ROLE %I LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION', rec.rolname);
  END LOOP;

  FOR rec IN
    SELECT member_role.rolname AS member_name,granted.rolname AS granted_name
    FROM pg_auth_members membership
    JOIN pg_roles member_role ON member_role.oid=membership.member
    JOIN pg_roles granted ON granted.oid=membership.roleid
    WHERE member_role.rolname IN ('opstrax_app','opstrax_system')
  LOOP
    EXECUTE format('REVOKE %I FROM %I',rec.granted_name,rec.member_name);
  END LOOP;
  -- Also remove every principal that could inherit or SET ROLE into either
  -- runtime identity. Checking only memberships held by the runtime role leaves
  -- an incoming privilege-escalation edge.
  FOR rec IN
    SELECT member_role.rolname AS member_name,granted.rolname AS granted_name
    FROM pg_auth_members membership
    JOIN pg_roles member_role ON member_role.oid=membership.member
    JOIN pg_roles granted ON granted.oid=membership.roleid
    WHERE granted.rolname IN ('opstrax_app','opstrax_system')
  LOOP
    EXECUTE format('REVOKE %I FROM %I',rec.granted_name,rec.member_name);
  END LOOP;

  -- Exact database/schema envelope: connect + usage, never DDL or temp objects.
  EXECUTE format('REVOKE CONNECT,TEMPORARY ON DATABASE %I FROM PUBLIC',current_database());
  EXECUTE format('REVOKE CREATE,TEMPORARY ON DATABASE %I FROM opstrax_app,opstrax_system',current_database());
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO opstrax_app,opstrax_system',current_database());
  REVOKE ALL ON SCHEMA public FROM PUBLIC;
  REVOKE ALL ON SCHEMA public FROM opstrax_app,opstrax_system;
  GRANT USAGE ON SCHEMA public TO opstrax_app,opstrax_system;
END
$roles$;

CREATE SCHEMA IF NOT EXISTS opstrax_security;
REVOKE ALL ON SCHEMA opstrax_security FROM PUBLIC;
REVOKE ALL ON SCHEMA opstrax_security FROM opstrax_app,opstrax_system;
GRANT USAGE ON SCHEMA opstrax_security TO opstrax_app,opstrax_system;

CREATE TABLE IF NOT EXISTS opstrax_security.tenant_ticket_key (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  key_material bytea NOT NULL CHECK (octet_length(key_material)=32),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
REVOKE ALL ON opstrax_security.tenant_ticket_key FROM PUBLIC,opstrax_app,opstrax_system;
INSERT INTO opstrax_security.tenant_ticket_key(singleton,key_material)
VALUES (true,public.gen_random_bytes(32))
ON CONFLICT(singleton) DO NOTHING;

CREATE OR REPLACE FUNCTION opstrax_security.issue_tenant_ticket(
  p_tenant_id bigint,
  p_backend_pid integer,
  p_txid bigint,
  p_ttl_seconds integer DEFAULT 120
) RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, opstrax_security
AS $function$
DECLARE
  issued_nonce text;
  expires_epoch bigint;
  payload text;
  signature text;
  secret bytea;
BEGIN
  IF session_user <> 'opstrax_system' THEN
    RAISE EXCEPTION 'tenant ticket issuance requires opstrax_system' USING ERRCODE='42501';
  END IF;
  IF p_tenant_id IS NULL OR p_tenant_id<=0 OR p_backend_pid IS NULL OR p_backend_pid<=0
     OR p_txid IS NULL OR p_txid<=0 OR p_ttl_seconds IS NULL
     OR p_ttl_seconds<5 OR p_ttl_seconds>300 THEN
    RAISE EXCEPTION 'invalid tenant ticket binding' USING ERRCODE='22023';
  END IF;
  SELECT key_material INTO STRICT secret
  FROM opstrax_security.tenant_ticket_key WHERE singleton;
  issued_nonce := encode(public.gen_random_bytes(16),'hex');
  expires_epoch := extract(epoch FROM clock_timestamp())::bigint+p_ttl_seconds;
  payload := concat_ws(':','v1',p_tenant_id,p_backend_pid,p_txid,expires_epoch,issued_nonce);
  signature := encode(public.hmac(convert_to(payload,'UTF8'),secret,'sha256'),'hex');
  RETURN payload||':'||signature;
END
$function$;

CREATE OR REPLACE FUNCTION opstrax_security.current_tenant_id()
RETURNS bigint
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, opstrax_security
AS $function$
DECLARE
  ticket text;
  fields text[];
  payload text;
  secret bytea;
  ticket_tenant bigint;
  ticket_pid integer;
  ticket_txid bigint;
  expires_epoch bigint;
  supplied_signature bytea;
  expected_signature bytea;
BEGIN
  -- session_user is the authenticated identity even inside SECURITY DEFINER.
  IF session_user <> 'opstrax_app' THEN RETURN NULL; END IF;
  ticket := NULLIF(current_setting('app.tenant_ticket',true),'');
  IF ticket IS NULL OR length(ticket)>320 THEN RETURN NULL; END IF;
  fields := string_to_array(ticket,':');
  IF cardinality(fields)<>7 OR fields[1]<>'v1'
     OR fields[2]!~'^[1-9][0-9]{0,18}$'
     OR fields[3]!~'^[1-9][0-9]{0,9}$'
     OR fields[4]!~'^[1-9][0-9]{0,18}$'
     OR fields[5]!~'^[1-9][0-9]{0,18}$'
     OR fields[6]!~'^[0-9a-f]{32}$'
     OR fields[7]!~'^[0-9a-f]{64}$' THEN RETURN NULL; END IF;

  ticket_tenant := fields[2]::bigint;
  ticket_pid := fields[3]::integer;
  ticket_txid := fields[4]::bigint;
  expires_epoch := fields[5]::bigint;
  IF ticket_pid<>pg_backend_pid()
     OR ticket_txid<>txid_current()::bigint
     OR expires_epoch<extract(epoch FROM statement_timestamp())::bigint THEN RETURN NULL; END IF;

  SELECT key_material INTO STRICT secret
  FROM opstrax_security.tenant_ticket_key WHERE singleton;
  payload := array_to_string(fields[1:6],':');
  supplied_signature := decode(fields[7],'hex');
  expected_signature := public.hmac(convert_to(payload,'UTF8'),secret,'sha256');
  IF supplied_signature<>expected_signature THEN RETURN NULL; END IF;
  RETURN ticket_tenant;
EXCEPTION WHEN OTHERS THEN
  -- Malformed, overflowed, missing-key, or otherwise invalid tickets fail closed.
  RETURN NULL;
END
$function$;

REVOKE ALL ON FUNCTION opstrax_security.issue_tenant_ticket(bigint,integer,bigint,integer) FROM PUBLIC,opstrax_app;
REVOKE ALL ON FUNCTION opstrax_security.issue_tenant_ticket(bigint,integer,bigint,integer) FROM opstrax_system;
GRANT EXECUTE ON FUNCTION opstrax_security.issue_tenant_ticket(bigint,integer,bigint,integer) TO opstrax_system;
REVOKE ALL ON FUNCTION opstrax_security.current_tenant_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION opstrax_security.current_tenant_id() FROM opstrax_app,opstrax_system;
GRANT EXECUTE ON FUNCTION opstrax_security.current_tenant_id() TO opstrax_app,opstrax_system;

CREATE OR REPLACE FUNCTION opstrax_security.special_policy_contract_valid()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $function$
WITH app_expr AS (
  SELECT table_name,column_name,prefix,command_name,policy_name,
    CASE command_name WHEN 'SELECT' THEN format('((%s IS NULL) OR (%s = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))',column_name,column_name)
      WHEN 'INSERT' THEN ''
      ELSE format('((%s IS NOT NULL) AND (%s = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))',column_name,column_name) END qual,
    CASE command_name WHEN 'SELECT' THEN '' WHEN 'DELETE' THEN ''
      ELSE format('((%s IS NOT NULL) AND (%s = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))',column_name,column_name) END check_expr
  FROM (VALUES ('roles','company_id','roles'),('report_catalog','tenant_id','report_catalog')) t(table_name,column_name,prefix)
  CROSS JOIN LATERAL (VALUES ('SELECT',prefix||'_app_select'),('INSERT',prefix||'_app_insert'),
    ('UPDATE',prefix||'_app_update'),('DELETE',prefix||'_app_delete')) c(command_name,policy_name)
), expected(table_name,policy_name,permissive,command_name,role_name,qual,check_expr) AS (
  SELECT table_name,policy_name,'PERMISSIVE',command_name,'opstrax_app',qual,check_expr FROM app_expr
  UNION ALL SELECT table_name,'system_control_plane','PERMISSIVE','ALL','opstrax_system','true','true'
    FROM (VALUES ('roles'),('report_catalog'),('role_permissions'),('user_mfa_status'),('user_locale_preferences')) s(table_name)
  UNION ALL VALUES
    ('role_permissions','role_permissions_app_select','PERMISSIVE','SELECT','opstrax_app','(EXISTS ( SELECT 1 FROM roles r WHERE ((r.id = role_permissions.role_id) AND ((r.company_id IS NULL) OR (r.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id))))))',''),
    ('role_permissions','role_permissions_app_insert','PERMISSIVE','INSERT','opstrax_app','', '(EXISTS ( SELECT 1 FROM roles r WHERE ((r.id = role_permissions.role_id) AND (r.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))'),
    ('role_permissions','role_permissions_app_update','PERMISSIVE','UPDATE','opstrax_app','(EXISTS ( SELECT 1 FROM roles r WHERE ((r.id = role_permissions.role_id) AND (r.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))','(EXISTS ( SELECT 1 FROM roles r WHERE ((r.id = role_permissions.role_id) AND (r.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))'),
    ('role_permissions','role_permissions_app_delete','PERMISSIVE','DELETE','opstrax_app','(EXISTS ( SELECT 1 FROM roles r WHERE ((r.id = role_permissions.role_id) AND (r.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))',''),
    ('user_mfa_status','tenant_ticket_app','PERMISSIVE','ALL','opstrax_app','(EXISTS ( SELECT 1 FROM users u WHERE ((u.id = user_mfa_status.user_id) AND (u.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))','(EXISTS ( SELECT 1 FROM users u WHERE ((u.id = user_mfa_status.user_id) AND (u.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))'),
    ('user_locale_preferences','tenant_ticket_app','PERMISSIVE','ALL','opstrax_app','(EXISTS ( SELECT 1 FROM users u WHERE ((u.id = user_locale_preferences.user_id) AND (u.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))','(EXISTS ( SELECT 1 FROM users u WHERE ((u.id = user_locale_preferences.user_id) AND (u.company_id = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id)))))')
), actual AS (
  SELECT tablename table_name,policyname policy_name,permissive,cmd command_name,array_to_string(roles,',') role_name,
    regexp_replace(COALESCE(qual,''),'\s+',' ','g') qual,
    regexp_replace(COALESCE(with_check,''),'\s+',' ','g') check_expr
  FROM pg_policies WHERE schemaname='public'
    AND tablename IN ('roles','report_catalog','role_permissions','user_mfa_status','user_locale_preferences')
)
SELECT (SELECT count(*) FROM expected)=19 AND (SELECT count(*) FROM actual)=19
  AND (SELECT count(*)=5 AND bool_and(c.relrowsecurity AND c.relforcerowsecurity)
       FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
       WHERE n.nspname='public'
         AND c.relname IN ('roles','report_catalog','role_permissions','user_mfa_status','user_locale_preferences'))
  AND NOT EXISTS(SELECT * FROM expected EXCEPT SELECT * FROM actual)
  AND NOT EXISTS(SELECT * FROM actual EXCEPT SELECT * FROM expected)
$function$;
REVOKE ALL ON FUNCTION opstrax_security.special_policy_contract_valid() FROM PUBLIC,opstrax_app,opstrax_system;
GRANT EXECUTE ON FUNCTION opstrax_security.special_policy_contract_valid() TO opstrax_system;

CREATE OR REPLACE FUNCTION opstrax_security.generic_policy_contract_valid()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $function$
WITH tenant_scope AS (
  SELECT c.relname table_name,
    CASE WHEN c.relname='companies' THEN 'id'
         WHEN EXISTS(SELECT 1 FROM information_schema.columns x WHERE x.table_schema='public' AND x.table_name=c.relname AND x.column_name='company_id' AND x.data_type='bigint') THEN 'company_id'
         ELSE 'tenant_id' END tenant_col
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind IN ('r','p')
    AND c.relname NOT IN ('platform_invoices','gps_gateway_replay','platform_impersonation_sessions','roles','report_catalog')
    AND (c.relname='companies' OR EXISTS(SELECT 1 FROM information_schema.columns x
      WHERE x.table_schema='public' AND x.table_name=c.relname
        AND x.column_name IN ('company_id','tenant_id') AND x.data_type='bigint'))
), expected(table_name,policy_name,permissive,command_name,role_name,qual,check_expr) AS (
  SELECT table_name,'tenant_ticket_app','PERMISSIVE','ALL','opstrax_app',
    format('(%s = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id))',tenant_col),
    format('(%s = ( SELECT opstrax_security.current_tenant_id() AS current_tenant_id))',tenant_col)
  FROM tenant_scope
  UNION ALL SELECT table_name,'system_control_plane','PERMISSIVE','ALL','opstrax_system','true','true' FROM tenant_scope
), actual AS (
  SELECT p.tablename,p.policyname,p.permissive,p.cmd,array_to_string(p.roles,','),
    regexp_replace(COALESCE(p.qual,''),'\s+',' ','g'),
    regexp_replace(COALESCE(p.with_check,''),'\s+',' ','g')
  FROM pg_policies p JOIN tenant_scope t ON t.table_name=p.tablename
  WHERE p.schemaname='public'
)
SELECT (SELECT count(*) FROM actual)=(SELECT count(*) FROM expected)
  AND NOT EXISTS(SELECT * FROM expected EXCEPT SELECT * FROM actual)
  AND NOT EXISTS(SELECT * FROM actual EXCEPT SELECT * FROM expected)
$function$;
REVOKE ALL ON FUNCTION opstrax_security.generic_policy_contract_valid() FROM PUBLIC,opstrax_app,opstrax_system;
GRANT EXECUTE ON FUNCTION opstrax_security.generic_policy_contract_valid() TO opstrax_system;

-- Remove all inherited/default object capabilities, then rebuild the exact lanes.
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM PUBLIC,opstrax_app,opstrax_system;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC,opstrax_app,opstrax_system;

DO $definer_acl$
DECLARE rec record;
BEGIN
  -- Legacy SECURITY DEFINER functions are an alternate authorization surface.
  -- No runtime identity may execute one except the two locked ticket functions.
  FOR rec IN
    SELECT p.oid::regprocedure::text AS signature
    FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE p.prosecdef
      AND NOT (n.nspname='opstrax_security' AND p.proname IN ('issue_tenant_ticket','current_tenant_id'))
  LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,opstrax_app,opstrax_system',rec.signature);
  END LOOP;
END
$definer_acl$;

DO $column_acl$
DECLARE rec record;
BEGIN
  -- Table ACL revocation does not remove independent column ACL entries.
  FOR rec IN
    SELECT n.nspname,c.relname,a.attname
    FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p') AND a.attnum>0
      AND NOT a.attisdropped AND a.attacl IS NOT NULL
  LOOP
    EXECUTE format('REVOKE ALL PRIVILEGES (%I) ON TABLE %I.%I FROM opstrax_app,opstrax_system',rec.attname,rec.nspname,rec.relname);
  END LOOP;
END
$column_acl$;

-- Compliance evidence was historically missing its tenant key even though its
-- contents are generated from tenant records. Backfill only when provenance is
-- unambiguous; an unresolved row stops the cutover for explicit quarantine.
CREATE TABLE IF NOT EXISTS public.compliance_evidence (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  company_id bigint,
  control_id varchar(50) NOT NULL,
  evidence_type varchar(100) NOT NULL,
  source_system varchar(100) NOT NULL,
  source_entity varchar(200),
  source_record_id bigint,
  title varchar(500) NOT NULL,
  safe_summary text,
  generated_at timestamptz NOT NULL DEFAULT now(),
  evidence_hash varchar(64),
  retention_until date,
  generated_by varchar(200)
);
ALTER TABLE public.compliance_evidence ADD COLUMN IF NOT EXISTS company_id bigint;
UPDATE public.compliance_evidence evidence
SET company_id=source.company_id
FROM (
  SELECT e.id,u.company_id
  FROM public.compliance_evidence e
  JOIN public.users u ON e.generated_by=('user:'||u.id::text)
  WHERE e.company_id IS NULL
) source
WHERE evidence.id=source.id;
DO $evidence_preflight$
BEGIN
  IF EXISTS (SELECT 1 FROM public.compliance_evidence WHERE company_id IS NULL) THEN
    RAISE EXCEPTION 'Stage 58 cannot infer company_id for % compliance evidence rows; quarantine/backfill explicitly before retry',
      (SELECT count(*) FROM public.compliance_evidence WHERE company_id IS NULL);
  END IF;
END
$evidence_preflight$;
ALTER TABLE public.compliance_evidence ALTER COLUMN company_id SET NOT NULL;
DO $evidence_fk$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.compliance_evidence'::regclass AND conname='fk_compliance_evidence_company') THEN
    ALTER TABLE public.compliance_evidence ADD CONSTRAINT fk_compliance_evidence_company FOREIGN KEY(company_id) REFERENCES public.companies(id) NOT VALID;
  END IF;
END
$evidence_fk$;
ALTER TABLE public.compliance_evidence VALIDATE CONSTRAINT fk_compliance_evidence_company;
CREATE INDEX IF NOT EXISTS idx_compliance_evidence_company_generated
  ON public.compliance_evidence(company_id,generated_at DESC);

-- This service-owned table is absent from the historical base SQL on a clean
-- production migration lane. Stage58 materializes the exact runtime contract so
-- the terminal security cutover never depends on an owner-capable app boot.
CREATE TABLE IF NOT EXISTS public.user_mfa_status (
  user_id bigint PRIMARY KEY,
  mfa_enabled boolean NOT NULL DEFAULT false,
  mfa_provider varchar(50),
  enrolled_at timestamptz,
  last_used_at timestamptz,
  recovery_codes_generated_at timestamptz,
  recovery_codes_remaining integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  mfa_secret text
);
DO $mfa_fk$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.user_mfa_status'::regclass AND conname='fk_mfa_user') THEN
    ALTER TABLE public.user_mfa_status ADD CONSTRAINT fk_mfa_user FOREIGN KEY(user_id) REFERENCES public.users(id) ON DELETE CASCADE NOT VALID;
  END IF;
END
$mfa_fk$;

DO $default_acl$
DECLARE rec record;
BEGIN
  FOR rec IN
    SELECT DISTINCT owner_role.rolname AS owner_name,d.defaclobjtype,grantee.rolname AS grantee_name
    FROM pg_default_acl d
    JOIN pg_namespace ns ON ns.oid=d.defaclnamespace AND ns.nspname='public'
    JOIN pg_roles owner_role ON owner_role.oid=d.defaclrole
    CROSS JOIN LATERAL aclexplode(d.defaclacl) acl
    JOIN pg_roles grantee ON grantee.oid=acl.grantee
    WHERE grantee.rolname IN ('opstrax_app','opstrax_system') AND d.defaclobjtype IN ('r','S')
  LOOP
    IF rec.defaclobjtype='r' THEN
      EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public REVOKE ALL ON TABLES FROM %I',rec.owner_name,rec.grantee_name);
    ELSE
      EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I',rec.owner_name,rec.grantee_name);
    END IF;
  END LOOP;
END
$default_acl$;

DO $tenant_contract$
DECLARE rec record; pol record; tenant_col text; seq_name text;
BEGIN
  FOR rec IN
    SELECT cls.relname AS table_name,
      CASE WHEN cls.relname='companies' THEN 'id'
           WHEN EXISTS (SELECT 1 FROM information_schema.columns c WHERE c.table_schema='public' AND c.table_name=cls.relname AND c.column_name='company_id' AND c.data_type='bigint') THEN 'company_id'
           ELSE 'tenant_id' END AS tenant_column
    FROM pg_class cls JOIN pg_namespace ns ON ns.oid=cls.relnamespace
    WHERE ns.nspname='public' AND cls.relkind IN ('r','p')
      AND cls.relname NOT IN ('platform_invoices','gps_gateway_replay','platform_impersonation_sessions')
      AND (cls.relname='companies' OR EXISTS (SELECT 1 FROM information_schema.columns c
        WHERE c.table_schema='public' AND c.table_name=cls.relname
          AND c.column_name IN ('company_id','tenant_id') AND c.data_type='bigint'))
  LOOP
    tenant_col:=rec.tenant_column;
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',rec.table_name);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY',rec.table_name);
    FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=rec.table_name LOOP
      EXECUTE format('DROP POLICY %I ON public.%I',pol.policyname,rec.table_name);
    END LOOP;
    EXECUTE format('CREATE POLICY tenant_ticket_app ON public.%I AS PERMISSIVE FOR ALL TO opstrax_app USING (%I=(SELECT opstrax_security.current_tenant_id())) WITH CHECK (%I=(SELECT opstrax_security.current_tenant_id()))',rec.table_name,tenant_col,tenant_col);
    EXECUTE format('CREATE POLICY system_control_plane ON public.%I AS PERMISSIVE FOR ALL TO opstrax_system USING (true) WITH CHECK (true)',rec.table_name);

    EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.%I TO opstrax_system',rec.table_name);
    IF rec.table_name='companies' THEN
      EXECUTE 'GRANT SELECT,UPDATE ON TABLE public.companies TO opstrax_app';
    ELSE
      EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.%I TO opstrax_app',rec.table_name);
    END IF;
    FOR seq_name IN
      SELECT seq.oid::regclass::text FROM pg_class tbl
      JOIN pg_namespace n ON n.oid=tbl.relnamespace AND n.nspname='public'
      JOIN pg_depend d ON d.refobjid=tbl.oid AND d.refobjsubid>0 AND d.deptype IN ('a','i')
      JOIN pg_class seq ON seq.oid=d.objid AND seq.relkind='S'
      WHERE tbl.relname=rec.table_name
    LOOP
      EXECUTE format('GRANT USAGE,SELECT ON SEQUENCE %s TO opstrax_system',seq_name);
      IF rec.table_name<>'companies' THEN EXECUTE format('GRANT USAGE,SELECT ON SEQUENCE %s TO opstrax_app',seq_name); END IF;
    END LOOP;
  END LOOP;

  -- Existing append/read-only and evidence contracts remain least privilege.
  FOR rec IN SELECT * FROM (VALUES
    ('authorization_decision_logs',true,false,false),('audit_logs',true,false,false),
    ('compliance_evidence',true,false,false),
    ('fleet_tms_shipment_events',true,false,false),('fleet_tms_cold_chain_event_log',true,false,false),
    ('fleet_tms_asset_events',true,false,false),('fleet_tms_barcode_scan_events',true,false,false),
    ('fleet_tms_rfid_events',true,false,false),('compliance_expiry_events',true,true,false),
    ('market_pack_branch_migration_audit',false,false,false),('access_review_items',true,true,false),
    ('access_reviews',true,true,false),('backup_verifications',true,false,false),
    ('company_security_settings',true,true,false),('compliance_audit_packages',true,true,false),
    ('compliance_violations',false,true,false),('data_retention_policies',true,true,false),
    ('driver_compliance_status',false,false,false),('export_requests',true,true,false),
    ('fleet_tms_branch_migration_audit',false,false,false),('hos_clocks',false,false,false),
    ('security_events',true,false,false),
    ('sso_connections',true,true,false),('tenant_market_packs',false,false,false),
    ('tenant_entitlements',false,false,false),('demo_fixture_versions',false,false,false),
    ('tenant_subscriptions',false,false,false),('vehicle_compliance_status',false,false,false),
    ('workforce_schedules',true,true,false),('mfa_login_challenge_consumptions',true,false,true)
  ) m(table_name,allow_insert,allow_update,allow_delete)
  LOOP
    CONTINUE WHEN to_regclass('public.'||rec.table_name) IS NULL;
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM opstrax_app',rec.table_name);
    EXECUTE format('GRANT SELECT ON TABLE public.%I TO opstrax_app',rec.table_name);
    IF rec.allow_insert THEN EXECUTE format('GRANT INSERT ON TABLE public.%I TO opstrax_app',rec.table_name); END IF;
    IF rec.allow_update THEN EXECUTE format('GRANT UPDATE ON TABLE public.%I TO opstrax_app',rec.table_name); END IF;
    IF rec.allow_delete THEN EXECUTE format('GRANT DELETE ON TABLE public.%I TO opstrax_app',rec.table_name); END IF;
    FOR seq_name IN SELECT seq.oid::regclass::text FROM pg_class tbl JOIN pg_namespace n ON n.oid=tbl.relnamespace AND n.nspname='public' JOIN pg_depend d ON d.refobjid=tbl.oid AND d.refobjsubid>0 AND d.deptype IN ('a','i') JOIN pg_class seq ON seq.oid=d.objid AND seq.relkind='S' WHERE tbl.relname=rec.table_name LOOP
      EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM opstrax_app',seq_name);
      IF rec.allow_insert THEN EXECUTE format('GRANT USAGE,SELECT ON SEQUENCE %s TO opstrax_app',seq_name); END IF;
    END LOOP;
  END LOOP;
END
$tenant_contract$;

-- The stream-ticket nonce ledger is intentionally not tenant-queryable: the app
-- may atomically issue a nonce but cannot enumerate or consume capabilities.
-- Stage58 runs last and must preserve Stage66's narrower infrastructure grants
-- after its schema-wide privilege reset.
DO $stream_nonce_contract$
DECLARE pol record;
BEGIN
  IF to_regclass('public.telemetry_stream_ticket_nonces') IS NOT NULL THEN
    ALTER TABLE public.telemetry_stream_ticket_nonces ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.telemetry_stream_ticket_nonces FORCE ROW LEVEL SECURITY;
    FOR pol IN SELECT policyname FROM pg_policies
      WHERE schemaname='public' AND tablename='telemetry_stream_ticket_nonces'
    LOOP
      EXECUTE format('DROP POLICY %I ON public.telemetry_stream_ticket_nonces',pol.policyname);
    END LOOP;
    CREATE POLICY stream_ticket_nonce_app_insert
      ON public.telemetry_stream_ticket_nonces FOR INSERT TO opstrax_app
      WITH CHECK (audit_company_id=(SELECT opstrax_security.current_tenant_id()));
    CREATE POLICY system_control_plane
      ON public.telemetry_stream_ticket_nonces FOR ALL TO opstrax_system
      USING (true) WITH CHECK (true);
    REVOKE ALL ON TABLE public.telemetry_stream_ticket_nonces FROM PUBLIC,opstrax_app,opstrax_system;
    GRANT INSERT ON TABLE public.telemetry_stream_ticket_nonces TO opstrax_app;
    GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.telemetry_stream_ticket_nonces TO opstrax_system;
  END IF;
  IF to_regclass('public.telemetry_stream_ticket_nonces_id_seq') IS NOT NULL THEN
    REVOKE ALL ON SEQUENCE public.telemetry_stream_ticket_nonces_id_seq FROM PUBLIC,opstrax_app,opstrax_system;
    GRANT USAGE ON SEQUENCE public.telemetry_stream_ticket_nonces_id_seq TO opstrax_app,opstrax_system;
  END IF;
END
$stream_nonce_contract$;

-- Roles include immutable global templates (company_id IS NULL). App reads those
-- plus its tenant roles, but can mutate only its tenant-owned rows. The per-command
-- policies prevent DELETE from bypassing a WITH CHECK intended for writes.
DO $role_contract$
DECLARE pol record;
BEGIN
  FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='roles' LOOP
    EXECUTE format('DROP POLICY %I ON public.roles',pol.policyname);
  END LOOP;
  CREATE POLICY roles_app_select ON roles FOR SELECT TO opstrax_app
    USING(company_id IS NULL OR company_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY roles_app_insert ON roles FOR INSERT TO opstrax_app
    WITH CHECK(company_id IS NOT NULL AND company_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY roles_app_update ON roles FOR UPDATE TO opstrax_app
    USING(company_id IS NOT NULL AND company_id=(SELECT opstrax_security.current_tenant_id()))
    WITH CHECK(company_id IS NOT NULL AND company_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY roles_app_delete ON roles FOR DELETE TO opstrax_app
    USING(company_id IS NOT NULL AND company_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY system_control_plane ON roles FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
END
$role_contract$;

DO $report_catalog_contract$
DECLARE pol record;
BEGIN
  FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='report_catalog' LOOP
    EXECUTE format('DROP POLICY %I ON public.report_catalog',pol.policyname);
  END LOOP;
  CREATE POLICY report_catalog_app_select ON report_catalog FOR SELECT TO opstrax_app
    USING(tenant_id IS NULL OR tenant_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY report_catalog_app_insert ON report_catalog FOR INSERT TO opstrax_app
    WITH CHECK(tenant_id IS NOT NULL AND tenant_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY report_catalog_app_update ON report_catalog FOR UPDATE TO opstrax_app
    USING(tenant_id IS NOT NULL AND tenant_id=(SELECT opstrax_security.current_tenant_id()))
    WITH CHECK(tenant_id IS NOT NULL AND tenant_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY report_catalog_app_delete ON report_catalog FOR DELETE TO opstrax_app
    USING(tenant_id IS NOT NULL AND tenant_id=(SELECT opstrax_security.current_tenant_id()));
  CREATE POLICY system_control_plane ON report_catalog FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
END
$report_catalog_contract$;

-- Tenant-derived child tables cannot carry a denormalized company_id. Their app
-- policies join to a ticket-filtered parent; system retains its explicit lane.
DO $derived_contract$
DECLARE pol record;
BEGIN
  IF EXISTS (SELECT 1 FROM user_locale_preferences p LEFT JOIN users u ON u.id=p.user_id WHERE p.user_id IS NULL OR u.id IS NULL) THEN
    RAISE EXCEPTION 'Stage 58 user_locale_preferences contains null/orphan user ownership';
  END IF;
  ALTER TABLE user_locale_preferences ALTER COLUMN user_id SET NOT NULL;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.user_locale_preferences'::regclass AND conname='fk_user_locale_preferences_user') THEN
    ALTER TABLE user_locale_preferences ADD CONSTRAINT fk_user_locale_preferences_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE NOT VALID;
  END IF;
  ALTER TABLE user_locale_preferences VALIDATE CONSTRAINT fk_user_locale_preferences_user;
  ALTER TABLE user_mfa_status VALIDATE CONSTRAINT fk_mfa_user;

  FOR pol IN SELECT tablename,policyname FROM pg_policies WHERE schemaname='public' AND tablename IN ('role_permissions','user_mfa_status','user_locale_preferences') LOOP
    EXECUTE format('DROP POLICY %I ON public.%I',pol.policyname,pol.tablename);
  END LOOP;
  ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY; ALTER TABLE role_permissions FORCE ROW LEVEL SECURITY;
  ALTER TABLE user_mfa_status ENABLE ROW LEVEL SECURITY; ALTER TABLE user_mfa_status FORCE ROW LEVEL SECURITY;
  ALTER TABLE user_locale_preferences ENABLE ROW LEVEL SECURITY; ALTER TABLE user_locale_preferences FORCE ROW LEVEL SECURITY;

  CREATE POLICY role_permissions_app_select ON role_permissions FOR SELECT TO opstrax_app
    USING (EXISTS (SELECT 1 FROM roles r WHERE r.id=role_id AND (r.company_id IS NULL OR r.company_id=(SELECT opstrax_security.current_tenant_id()))));
  CREATE POLICY role_permissions_app_insert ON role_permissions FOR INSERT TO opstrax_app
    WITH CHECK (EXISTS (SELECT 1 FROM roles r WHERE r.id=role_id AND r.company_id=(SELECT opstrax_security.current_tenant_id())));
  CREATE POLICY role_permissions_app_update ON role_permissions FOR UPDATE TO opstrax_app
    USING (EXISTS (SELECT 1 FROM roles r WHERE r.id=role_id AND r.company_id=(SELECT opstrax_security.current_tenant_id())))
    WITH CHECK (EXISTS (SELECT 1 FROM roles r WHERE r.id=role_id AND r.company_id=(SELECT opstrax_security.current_tenant_id())));
  CREATE POLICY role_permissions_app_delete ON role_permissions FOR DELETE TO opstrax_app
    USING (EXISTS (SELECT 1 FROM roles r WHERE r.id=role_id AND r.company_id=(SELECT opstrax_security.current_tenant_id())));
  CREATE POLICY system_control_plane ON role_permissions FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
  CREATE POLICY tenant_ticket_app ON user_mfa_status FOR ALL TO opstrax_app
    USING (EXISTS (SELECT 1 FROM users u WHERE u.id=user_id AND u.company_id=(SELECT opstrax_security.current_tenant_id())))
    WITH CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id=user_id AND u.company_id=(SELECT opstrax_security.current_tenant_id())));
  CREATE POLICY system_control_plane ON user_mfa_status FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
  CREATE POLICY tenant_ticket_app ON user_locale_preferences FOR ALL TO opstrax_app
    USING (EXISTS (SELECT 1 FROM users u WHERE u.id=user_id AND u.company_id=(SELECT opstrax_security.current_tenant_id())))
    WITH CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id=user_id AND u.company_id=(SELECT opstrax_security.current_tenant_id())));
  CREATE POLICY system_control_plane ON user_locale_preferences FOR ALL TO opstrax_system USING(true) WITH CHECK(true);

  GRANT SELECT,INSERT,UPDATE,DELETE ON role_permissions,user_mfa_status,user_locale_preferences TO opstrax_app,opstrax_system;
  GRANT USAGE,SELECT ON SEQUENCE role_permissions_id_seq,user_locale_preferences_id_seq TO opstrax_app,opstrax_system;
END
$derived_contract$;

-- Non-tenant catalogs consumed by tenant UI are explicitly read-only. No sequence
-- capability is granted. Platform/control-plane and service ledgers are system-only.
DO $global_contract$
DECLARE rec record; seq_rec record; pol record;
BEGIN
  FOR rec IN SELECT name FROM (VALUES
    ('compliance_controls'),('compliance_profiles'),('compliance_rules'),
    ('countries'),('country_profiles'),('fleet_tms_saudi_regions'),('inspection_items'),('languages'),
    ('market_address_schemas'),('market_currency_settings'),('market_document_types'),
    ('market_driver_requirements'),('market_inspection_templates'),('market_language_settings'),
    ('market_pack_features'),('market_packs'),('market_tax_reporting_rules'),('market_unit_settings'),
    ('market_vehicle_requirements'),('module_packages'),('packages'),('permissions'),
    ('pricing_rules'),('usage_meters')
  ) refs(name) LOOP
    IF to_regclass('public.'||rec.name) IS NOT NULL THEN
      EXECUTE format('GRANT SELECT ON TABLE public.%I TO opstrax_app',rec.name);
    END IF;
  END LOOP;

  -- System is the only runtime identity for non-tenant operational/control data.
  FOR rec IN SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p')
      AND c.relname NOT IN ('role_permissions','user_mfa_status','user_locale_preferences','platform_data_protection_keys')
      AND c.relname<>'companies'
      AND NOT EXISTS (SELECT 1 FROM information_schema.columns x WHERE x.table_schema='public' AND x.table_name=c.relname AND x.column_name IN ('company_id','tenant_id') AND x.data_type='bigint')
  LOOP EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.%I TO opstrax_system',rec.relname); END LOOP;
  FOR seq_rec IN SELECT c.oid::regclass::text AS seq_name FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind='S'
      AND c.relname<>'telemetry_stream_ticket_nonces_id_seq'
  LOOP EXECUTE format('GRANT USAGE,SELECT ON SEQUENCE %s TO opstrax_system',seq_rec.seq_name); END LOOP;

  -- Audited exclusions from the tenant-column heuristic are system-only.
  IF to_regclass('public.platform_invoices') IS NOT NULL THEN
    ALTER TABLE public.platform_invoices ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.platform_invoices FORCE ROW LEVEL SECURITY;
    FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='platform_invoices' LOOP
      EXECUTE format('DROP POLICY %I ON public.platform_invoices',pol.policyname);
    END LOOP;
    CREATE POLICY system_control_plane ON public.platform_invoices FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
    GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.platform_invoices TO opstrax_system;
  END IF;
  IF to_regclass('public.gps_gateway_replay') IS NOT NULL THEN
    ALTER TABLE public.gps_gateway_replay ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.gps_gateway_replay FORCE ROW LEVEL SECURITY;
    FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='gps_gateway_replay' LOOP
      EXECUTE format('DROP POLICY %I ON public.gps_gateway_replay',pol.policyname);
    END LOOP;
    CREATE POLICY system_control_plane ON public.gps_gateway_replay FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
    GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.gps_gateway_replay TO opstrax_system;
  END IF;
  IF to_regclass('public.platform_impersonation_sessions') IS NOT NULL THEN
    ALTER TABLE public.platform_impersonation_sessions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.platform_impersonation_sessions FORCE ROW LEVEL SECURITY;
    FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='platform_impersonation_sessions' LOOP
      EXECUTE format('DROP POLICY %I ON public.platform_impersonation_sessions',pol.policyname);
    END LOOP;
    CREATE POLICY system_control_plane ON public.platform_impersonation_sessions FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
    GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.platform_impersonation_sessions TO opstrax_system;
  END IF;
  IF to_regclass('public.platform_data_protection_keys') IS NOT NULL THEN
    ALTER TABLE public.platform_data_protection_keys ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.platform_data_protection_keys FORCE ROW LEVEL SECURITY;
    FOR pol IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='platform_data_protection_keys' LOOP
      EXECUTE format('DROP POLICY %I ON public.platform_data_protection_keys',pol.policyname);
    END LOOP;
    CREATE POLICY system_control_plane ON public.platform_data_protection_keys FOR ALL TO opstrax_system USING(true) WITH CHECK(true);
    GRANT SELECT,INSERT ON TABLE public.platform_data_protection_keys TO opstrax_system;
  END IF;
END
$global_contract$;

DO $verify$
DECLARE violations text[];
BEGIN
  -- Managed Postgres (Neon/RDS/Cloud SQL) auto-grants the database owner ADMIN membership
  -- in every role created under it, and records the grant with the provider's internal
  -- superuser as grantor (e.g. Neon's cloud_admin). The customer-visible owner therefore
  -- CANNOT revoke it — REVOKE is a no-op warning — which made this contract unsatisfiable
  -- on every managed provider. That single membership grants no privilege the database
  -- owner does not already hold, so it is not an escalation edge. Keep both directions
  -- strict for every other principal: the runtime identity must still never be a member of
  -- anything, and no principal other than the database owner may SET ROLE into it.
  IF NOT EXISTS (SELECT 1 FROM pg_roles r WHERE r.rolname='opstrax_app' AND r.rolcanlogin AND NOT r.rolsuper AND NOT r.rolbypassrls AND NOT r.rolcreatedb AND NOT r.rolcreaterole AND NOT r.rolinherit AND NOT r.rolreplication
       AND NOT EXISTS(SELECT 1 FROM pg_auth_members m WHERE m.member=r.oid)
       AND NOT EXISTS(SELECT 1 FROM pg_auth_members m WHERE m.roleid=r.oid AND m.member<>(SELECT d.datdba FROM pg_database d WHERE d.datname=current_database())))
     OR NOT EXISTS (SELECT 1 FROM pg_roles r WHERE r.rolname='opstrax_system' AND r.rolcanlogin AND NOT r.rolsuper AND NOT r.rolbypassrls AND NOT r.rolcreatedb AND NOT r.rolcreaterole AND NOT r.rolinherit AND NOT r.rolreplication
       AND NOT EXISTS(SELECT 1 FROM pg_auth_members m WHERE m.member=r.oid)
       AND NOT EXISTS(SELECT 1 FROM pg_auth_members m WHERE m.roleid=r.oid AND m.member<>(SELECT d.datdba FROM pg_database d WHERE d.datname=current_database()))) THEN
    RAISE EXCEPTION 'Stage 58 runtime role attributes/memberships unsafe';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_database d CROSS JOIN LATERAL aclexplode(COALESCE(d.datacl,acldefault('d',d.datdba))) acl
       WHERE d.datname=current_database() AND acl.grantee=0 AND acl.privilege_type IN ('CONNECT','TEMPORARY'))
     OR NOT has_database_privilege('opstrax_app',current_database(),'CONNECT')
     OR NOT has_database_privilege('opstrax_system',current_database(),'CONNECT')
     OR has_database_privilege('opstrax_app',current_database(),'CREATE,TEMPORARY')
     OR has_database_privilege('opstrax_system',current_database(),'CREATE,TEMPORARY')
     OR EXISTS(SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(COALESCE(n.nspacl,acldefault('n',n.nspowner))) acl
       WHERE n.nspname='public' AND acl.grantee=0 AND acl.privilege_type IN ('USAGE','CREATE'))
     OR NOT has_schema_privilege('opstrax_app','public','USAGE')
     OR NOT has_schema_privilege('opstrax_system','public','USAGE')
     OR has_schema_privilege('opstrax_app','public','CREATE')
     OR has_schema_privilege('opstrax_system','public','CREATE') THEN
    RAISE EXCEPTION 'Stage 58 database/schema ACL envelope unsafe';
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_roles runtime
    WHERE runtime.rolname IN ('opstrax_app','opstrax_system') AND (
      EXISTS(SELECT 1 FROM pg_database d WHERE d.datdba=runtime.oid)
      OR EXISTS(SELECT 1 FROM pg_namespace n WHERE n.nspowner=runtime.oid)
      OR EXISTS(SELECT 1 FROM pg_class c WHERE c.relowner=runtime.oid)
      OR EXISTS(SELECT 1 FROM pg_proc p WHERE p.proowner=runtime.oid)
      OR EXISTS(SELECT 1 FROM pg_type t WHERE t.typowner=runtime.oid))) THEN
    RAISE EXCEPTION 'Stage 58 runtime identity owns database objects';
  END IF;
  IF (SELECT nspowner FROM pg_namespace WHERE nspname='opstrax_security')
       IN ((SELECT oid FROM pg_roles WHERE rolname='opstrax_app'),(SELECT oid FROM pg_roles WHERE rolname='opstrax_system'))
     OR (SELECT relowner FROM pg_class WHERE oid='opstrax_security.tenant_ticket_key'::regclass)
       IN ((SELECT oid FROM pg_roles WHERE rolname='opstrax_app'),(SELECT oid FROM pg_roles WHERE rolname='opstrax_system'))
     OR EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='opstrax_security' AND p.proname IN ('issue_tenant_ticket','current_tenant_id')
         AND p.proowner IN ((SELECT oid FROM pg_roles WHERE rolname='opstrax_app'),(SELECT oid FROM pg_roles WHERE rolname='opstrax_system'))) THEN
    RAISE EXCEPTION 'Stage 58 protected security objects are runtime-owned';
  END IF;
  IF (SELECT relowner FROM pg_class WHERE oid='opstrax_security.tenant_ticket_key'::regclass)
       <> (SELECT nspowner FROM pg_namespace WHERE nspname='opstrax_security') THEN
    RAISE EXCEPTION 'Stage 58 protected security owner graph drifted';
  END IF;
  IF has_function_privilege('opstrax_app','opstrax_security.issue_tenant_ticket(bigint,integer,bigint,integer)','EXECUTE')
     OR NOT has_function_privilege('opstrax_system','opstrax_security.issue_tenant_ticket(bigint,integer,bigint,integer)','EXECUTE')
     OR NOT has_function_privilege('opstrax_app','opstrax_security.current_tenant_id()','EXECUTE')
     OR has_table_privilege('opstrax_app','opstrax_security.tenant_ticket_key','SELECT')
     OR has_table_privilege('opstrax_system','opstrax_security.tenant_ticket_key','SELECT') THEN
    RAISE EXCEPTION 'Stage 58 ticket function/key privileges unsafe';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE p.prosecdef
      AND NOT (n.nspname='opstrax_security' AND p.proname='current_tenant_id' AND p.pronargs=0)
      AND has_function_privilege('opstrax_app',p.oid,'EXECUTE')) THEN
    RAISE EXCEPTION 'Stage 58 app can execute a non-allowlisted SECURITY DEFINER function';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE p.prosecdef
      AND NOT (n.nspname='opstrax_security' AND ((p.proname='current_tenant_id' AND p.pronargs=0)
        OR (p.proname='issue_tenant_ticket' AND p.pronargs=4)))
      AND has_function_privilege('opstrax_system',p.oid,'EXECUTE')) THEN
    RAISE EXCEPTION 'Stage 58 system can execute a non-allowlisted SECURITY DEFINER function';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='opstrax_security' AND p.proname IN ('issue_tenant_ticket','current_tenant_id')
      AND (NOT p.prosecdef OR p.proowner<>(SELECT n2.nspowner FROM pg_namespace n2 WHERE n2.nspname='opstrax_security')
        OR p.proconfig IS DISTINCT FROM ARRAY['search_path=pg_catalog, opstrax_security']::text[])) THEN
    RAISE EXCEPTION 'Stage 58 ticket function owner/security/search_path drifted';
  END IF;
  IF has_table_privilege('opstrax_app','platform_admins','SELECT')
     OR has_table_privilege('opstrax_app','platform_sessions','SELECT')
     OR has_table_privilege('opstrax_app','platform_audit_log','SELECT')
     OR has_table_privilege('opstrax_app','platform_roles','SELECT')
     OR has_table_privilege('opstrax_app','platform_role_permissions','SELECT')
     OR has_table_privilege('opstrax_app','schema_migrations','SELECT')
     OR has_table_privilege('opstrax_app','service_heartbeats','SELECT')
     OR has_table_privilege('opstrax_app','service_run_history','SELECT')
     OR has_table_privilege('opstrax_app','telemetry_nonces','SELECT') THEN
    RAISE EXCEPTION 'Stage 58 app retains control-plane/system-ledger access';
  END IF;
  IF to_regclass('public.telemetry_stream_ticket_nonces') IS NOT NULL AND (
       NOT (SELECT relrowsecurity AND relforcerowsecurity FROM pg_class
            WHERE oid='public.telemetry_stream_ticket_nonces'::regclass)
       OR (SELECT count(*) FROM pg_policies
           WHERE schemaname='public' AND tablename='telemetry_stream_ticket_nonces')<>2
       OR NOT EXISTS (SELECT 1 FROM pg_policies
           WHERE schemaname='public' AND tablename='telemetry_stream_ticket_nonces'
             AND policyname='stream_ticket_nonce_app_insert' AND cmd='INSERT'
             AND roles='{opstrax_app}'::name[] AND qual IS NULL
             AND with_check LIKE '%opstrax_security.current_tenant_id()%')
       OR NOT EXISTS (SELECT 1 FROM pg_policies
           WHERE schemaname='public' AND tablename='telemetry_stream_ticket_nonces'
             AND policyname='system_control_plane' AND cmd='ALL'
             AND roles='{opstrax_system}'::name[] AND qual='true' AND with_check='true')
       OR NOT has_table_privilege('opstrax_app','telemetry_stream_ticket_nonces','INSERT')
       OR has_table_privilege('opstrax_app','telemetry_stream_ticket_nonces','SELECT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
       OR NOT has_table_privilege('opstrax_system','telemetry_stream_ticket_nonces','SELECT')
       OR NOT has_table_privilege('opstrax_system','telemetry_stream_ticket_nonces','INSERT')
       OR NOT has_table_privilege('opstrax_system','telemetry_stream_ticket_nonces','UPDATE')
       OR NOT has_table_privilege('opstrax_system','telemetry_stream_ticket_nonces','DELETE')
       OR has_table_privilege('opstrax_system','telemetry_stream_ticket_nonces','TRUNCATE,REFERENCES,TRIGGER')) THEN
    RAISE EXCEPTION 'Stage 58 stream-ticket nonce table boundary unsafe';
  END IF;
  IF to_regclass('public.telemetry_stream_ticket_nonces_id_seq') IS NOT NULL AND (
       NOT has_sequence_privilege('opstrax_app','telemetry_stream_ticket_nonces_id_seq','USAGE')
       OR has_sequence_privilege('opstrax_app','telemetry_stream_ticket_nonces_id_seq','SELECT')
       OR has_sequence_privilege('opstrax_app','telemetry_stream_ticket_nonces_id_seq','UPDATE')
       OR NOT has_sequence_privilege('opstrax_system','telemetry_stream_ticket_nonces_id_seq','USAGE')
       OR has_sequence_privilege('opstrax_system','telemetry_stream_ticket_nonces_id_seq','SELECT')
       OR has_sequence_privilege('opstrax_system','telemetry_stream_ticket_nonces_id_seq','UPDATE')
       OR has_sequence_privilege('public','telemetry_stream_ticket_nonces_id_seq','USAGE,SELECT,UPDATE')) THEN
    RAISE EXCEPTION 'Stage 58 stream-ticket nonce sequence boundary unsafe';
  END IF;
  IF has_any_column_privilege('opstrax_app','platform_admins','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','platform_sessions','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','platform_audit_log','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','schema_migrations','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','service_heartbeats','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','service_run_history','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_any_column_privilege('opstrax_app','telemetry_nonces','SELECT,INSERT,UPDATE,REFERENCES') THEN
    RAISE EXCEPTION 'Stage 58 app retains system-only column access';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_attribute a CROSS JOIN LATERAL aclexplode(a.attacl) acl
    JOIN pg_roles r ON r.oid=acl.grantee WHERE r.rolname IN ('opstrax_app','opstrax_system')) THEN
    RAISE EXCEPTION 'Stage 58 unexpected runtime column ACL remains';
  END IF;
  SELECT array_agg(s.table_name ORDER BY s.table_name) INTO violations FROM (
    SELECT c.relname table_name FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p')
      AND c.relname NOT IN ('platform_invoices','gps_gateway_replay','platform_impersonation_sessions')
      AND (c.relname='companies' OR EXISTS(SELECT 1 FROM information_schema.columns x WHERE x.table_schema='public' AND x.table_name=c.relname AND x.column_name IN ('company_id','tenant_id') AND x.data_type='bigint'))
  ) s WHERE s.table_name NOT IN ('roles','report_catalog') AND ((SELECT count(*) FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=s.table_name)<>2
    OR NOT EXISTS(SELECT 1 FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=s.table_name AND p.policyname='tenant_ticket_app' AND p.roles='{opstrax_app}'::name[]
      AND p.cmd='ALL' AND p.qual LIKE '%opstrax_security.current_tenant_id()%' AND p.qual LIKE '%SELECT%' AND p.with_check=p.qual)
    OR NOT EXISTS(SELECT 1 FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=s.table_name AND p.policyname='system_control_plane' AND p.roles='{opstrax_system}'::name[]
      AND p.cmd='ALL' AND p.qual='true' AND p.with_check='true'));
  IF cardinality(violations)>0 THEN RAISE EXCEPTION 'Stage 58 tenant policy violations: %',violations; END IF;
  IF EXISTS(
    SELECT 1 FROM (VALUES
      ('roles','roles_app_select','SELECT','opstrax_app'),
      ('roles','roles_app_insert','INSERT','opstrax_app'),
      ('roles','roles_app_update','UPDATE','opstrax_app'),
      ('roles','roles_app_delete','DELETE','opstrax_app'),
      ('roles','system_control_plane','ALL','opstrax_system'),
      ('report_catalog','report_catalog_app_select','SELECT','opstrax_app'),
      ('report_catalog','report_catalog_app_insert','INSERT','opstrax_app'),
      ('report_catalog','report_catalog_app_update','UPDATE','opstrax_app'),
      ('report_catalog','report_catalog_app_delete','DELETE','opstrax_app'),
      ('report_catalog','system_control_plane','ALL','opstrax_system'),
      ('role_permissions','role_permissions_app_select','SELECT','opstrax_app'),
      ('role_permissions','role_permissions_app_insert','INSERT','opstrax_app'),
      ('role_permissions','role_permissions_app_update','UPDATE','opstrax_app'),
      ('role_permissions','role_permissions_app_delete','DELETE','opstrax_app'),
      ('role_permissions','system_control_plane','ALL','opstrax_system'),
      ('user_mfa_status','tenant_ticket_app','ALL','opstrax_app'),
      ('user_mfa_status','system_control_plane','ALL','opstrax_system'),
      ('user_locale_preferences','tenant_ticket_app','ALL','opstrax_app'),
      ('user_locale_preferences','system_control_plane','ALL','opstrax_system')
    ) expected(table_name,policy_name,command_name,role_name)
    LEFT JOIN pg_policies p ON p.schemaname='public' AND p.tablename=expected.table_name
      AND p.policyname=expected.policy_name AND p.cmd=expected.command_name
      AND p.roles=ARRAY[expected.role_name]::name[]
    WHERE p.policyname IS NULL
  ) OR EXISTS(
    SELECT 1 FROM (VALUES ('roles',5),('report_catalog',5),('role_permissions',5),
      ('user_mfa_status',2),('user_locale_preferences',2)) expected(table_name,policy_count)
    WHERE (SELECT count(*) FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=expected.table_name)<>expected.policy_count
  ) THEN
    RAISE EXCEPTION 'Stage 58 special/derived policy allow-list drifted';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_policies p
      WHERE p.schemaname='public' AND p.tablename IN ('roles','report_catalog','role_permissions','user_mfa_status','user_locale_preferences')
        AND (p.roles='{public}'::name[] OR COALESCE(p.qual,'') LIKE '%current_setting%'
          OR COALESCE(p.with_check,'') LIKE '%current_setting%'))
     OR EXISTS(SELECT 1 FROM pg_policies p WHERE p.schemaname='public'
       AND p.tablename IN ('roles','report_catalog','role_permissions')
       AND p.roles='{opstrax_app}'::name[] AND p.cmd='SELECT'
       AND (p.qual NOT LIKE '%IS NULL%' OR p.qual NOT LIKE '%opstrax_security.current_tenant_id()%'))
     OR EXISTS(SELECT 1 FROM pg_policies p WHERE p.schemaname='public'
       AND p.tablename IN ('roles','report_catalog','role_permissions')
       AND p.roles='{opstrax_app}'::name[] AND p.cmd IN ('INSERT','UPDATE','DELETE')
       AND COALESCE(p.qual,p.with_check,'') NOT LIKE '%opstrax_security.current_tenant_id()%')
     OR EXISTS(SELECT 1 FROM pg_policies p WHERE p.schemaname='public'
       AND p.tablename IN ('user_mfa_status','user_locale_preferences')
       AND p.policyname='tenant_ticket_app'
       AND (p.qual NOT LIKE '%FROM users%' OR p.qual NOT LIKE '%opstrax_security.current_tenant_id()%'
         OR p.with_check IS DISTINCT FROM p.qual)) THEN
    RAISE EXCEPTION 'Stage 58 special/derived policy expression drifted';
  END IF;
  IF NOT opstrax_security.special_policy_contract_valid() THEN
    RAISE EXCEPTION 'Stage 58 exact special/derived policy contract drifted';
  END IF;
  IF NOT opstrax_security.generic_policy_contract_valid() THEN
    RAISE EXCEPTION 'Stage 58 exact generic tenant policy contract drifted';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p')
      AND c.relname NOT IN ('platform_invoices','gps_gateway_replay','platform_impersonation_sessions','roles','report_catalog')
      AND (c.relname='companies' OR EXISTS (SELECT 1 FROM information_schema.columns x
        WHERE x.table_schema='public' AND x.table_name=c.relname
          AND x.column_name IN ('company_id','tenant_id') AND x.data_type='bigint'))
      AND (NOT has_table_privilege('opstrax_system',c.oid,'SELECT')
        OR NOT has_table_privilege('opstrax_system',c.oid,'INSERT')
        OR NOT has_table_privilege('opstrax_system',c.oid,'UPDATE')
        OR NOT has_table_privilege('opstrax_system',c.oid,'DELETE')
        OR has_table_privilege('opstrax_system',c.oid,'TRUNCATE,REFERENCES,TRIGGER'))) THEN
    RAISE EXCEPTION 'Stage 58 generic system table privilege contract unsafe';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_class tbl JOIN pg_namespace n ON n.oid=tbl.relnamespace
    JOIN pg_depend d ON d.refobjid=tbl.oid AND d.refobjsubid>0 AND d.deptype IN ('a','i')
    JOIN pg_class seq ON seq.oid=d.objid AND seq.relkind='S'
    WHERE n.nspname='public' AND tbl.relkind IN ('r','p')
      AND tbl.relname NOT IN ('platform_invoices','gps_gateway_replay','platform_impersonation_sessions','roles','report_catalog')
      AND (tbl.relname='companies' OR EXISTS (SELECT 1 FROM information_schema.columns x
        WHERE x.table_schema='public' AND x.table_name=tbl.relname
          AND x.column_name IN ('company_id','tenant_id') AND x.data_type='bigint'))
      AND (NOT has_sequence_privilege('opstrax_system',seq.oid,'USAGE')
        OR NOT has_sequence_privilege('opstrax_system',seq.oid,'SELECT')
        OR has_sequence_privilege('opstrax_system',seq.oid,'UPDATE'))) THEN
    RAISE EXCEPTION 'Stage 58 generic system sequence privilege contract unsafe';
  END IF;
  IF EXISTS (SELECT 1 FROM (VALUES
      ('roles'),('report_catalog'),('role_permissions'),('user_mfa_status'),('user_locale_preferences')
    ) expected(table_name)
    WHERE NOT has_table_privilege('opstrax_app','public.'||expected.table_name,'SELECT')
      OR NOT has_table_privilege('opstrax_app','public.'||expected.table_name,'INSERT')
      OR NOT has_table_privilege('opstrax_app','public.'||expected.table_name,'UPDATE')
      OR NOT has_table_privilege('opstrax_app','public.'||expected.table_name,'DELETE')
      OR has_table_privilege('opstrax_app','public.'||expected.table_name,'TRUNCATE,REFERENCES,TRIGGER')
      OR NOT has_table_privilege('opstrax_system','public.'||expected.table_name,'SELECT')
      OR NOT has_table_privilege('opstrax_system','public.'||expected.table_name,'INSERT')
      OR NOT has_table_privilege('opstrax_system','public.'||expected.table_name,'UPDATE')
      OR NOT has_table_privilege('opstrax_system','public.'||expected.table_name,'DELETE')
      OR has_table_privilege('opstrax_system','public.'||expected.table_name,'TRUNCATE,REFERENCES,TRIGGER')) THEN
    RAISE EXCEPTION 'Stage 58 special/derived table privilege contract unsafe';
  END IF;
  IF EXISTS (SELECT 1 FROM (VALUES
      ('roles_id_seq'),('report_catalog_id_seq'),('role_permissions_id_seq'),('user_locale_preferences_id_seq')
    ) expected(sequence_name)
    WHERE NOT has_sequence_privilege('opstrax_app','public.'||expected.sequence_name,'USAGE')
      OR NOT has_sequence_privilege('opstrax_app','public.'||expected.sequence_name,'SELECT')
      OR has_sequence_privilege('opstrax_app','public.'||expected.sequence_name,'UPDATE')
      OR NOT has_sequence_privilege('opstrax_system','public.'||expected.sequence_name,'USAGE')
      OR NOT has_sequence_privilege('opstrax_system','public.'||expected.sequence_name,'SELECT')
      OR has_sequence_privilege('opstrax_system','public.'||expected.sequence_name,'UPDATE')) THEN
    RAISE EXCEPTION 'Stage 58 special/derived sequence privilege contract unsafe';
  END IF;
  IF NOT has_table_privilege('opstrax_app','companies','SELECT') OR NOT has_table_privilege('opstrax_app','companies','UPDATE')
     OR has_table_privilege('opstrax_app','companies','INSERT') OR has_table_privilege('opstrax_app','companies','DELETE')
     OR NOT has_table_privilege('opstrax_system','companies','SELECT')
     OR NOT has_table_privilege('opstrax_system','companies','INSERT')
     OR NOT has_table_privilege('opstrax_system','companies','UPDATE')
     OR NOT has_table_privilege('opstrax_system','companies','DELETE') THEN
    RAISE EXCEPTION 'Stage 58 companies privilege contract unsafe';
  END IF;
  IF EXISTS(SELECT 1 FROM (VALUES
      ('compliance_evidence',true,false,false),
      ('tenant_market_packs',false,false,false),
      ('tenant_entitlements',false,false,false),('demo_fixture_versions',false,false,false),
      ('tenant_subscriptions',false,false,false)
    ) expected(table_name,allow_insert,allow_update,allow_delete)
    WHERE NOT has_table_privilege('opstrax_app','public.'||expected.table_name,'SELECT')
      OR has_table_privilege('opstrax_app','public.'||expected.table_name,'INSERT')<>expected.allow_insert
      OR has_table_privilege('opstrax_app','public.'||expected.table_name,'UPDATE')<>expected.allow_update
      OR has_table_privilege('opstrax_app','public.'||expected.table_name,'DELETE')<>expected.allow_delete) THEN
    RAISE EXCEPTION 'Stage 58 commercial/evidence least-privilege matrix unsafe';
  END IF;
  IF has_table_privilege('opstrax_app','platform_impersonation_sessions','SELECT')
     OR NOT has_table_privilege('opstrax_system','platform_impersonation_sessions','SELECT')
     OR NOT has_table_privilege('opstrax_system','platform_impersonation_sessions','INSERT')
     OR NOT has_table_privilege('opstrax_system','platform_impersonation_sessions','UPDATE')
     OR NOT has_table_privilege('opstrax_system','platform_impersonation_sessions','DELETE') THEN
    RAISE EXCEPTION 'Stage 58 platform impersonation lane unsafe';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) a JOIN pg_roles r ON r.oid=a.grantee WHERE r.rolname IN ('opstrax_app','opstrax_system') AND d.defaclobjtype IN ('r','S')) THEN
    RAISE EXCEPTION 'Stage 58 broad runtime default ACL remains';
  END IF;
END
$verify$;

INSERT INTO schema_migrations(version,description)
VALUES ('2026_07_31_stage58_nonforgeable_tenant_ticket','Non-forgeable transaction-bound tenant ticket and dual runtime identities')
ON CONFLICT(version) DO UPDATE SET description=EXCLUDED.description;

COMMIT;
