-- Stage 25 — Branch / Depot / Yard org hierarchy (P1-6)
--
-- PURPOSE
--   Enterprise fleets are organised into branches (regional offices) and depots/
--   yards (physical sites). Competitors (Samsara/Motive/Geotab) all model this, and
--   a branch manager must see only their branch's fleet. OpsTrax had a FLAT org
--   (tenant -> users), with no way to scope a user/vehicle/driver to a branch.
--
--   This adds a `branches` table (type = branch | depot | yard) under company_id, and
--   an optional branch_id FK on users, vehicles, and drivers. branch_id NULL = "all
--   branches" (tenant-wide), preserving existing behavior. RLS still isolates by
--   company; branch scoping is an ADDITIONAL in-app filter layer beneath tenant
--   isolation (a branch manager gets rows for their branch only; NULL-branch users
--   see everything in the tenant).
--
-- SAFETY / REVERSIBILITY
--   Additive (CREATE TABLE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS). Idempotent.
--   No data mutated; existing users/vehicles/drivers get branch_id NULL (tenant-wide).

BEGIN;

CREATE TABLE IF NOT EXISTS branches (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    bigint NOT NULL,
    branch_code   varchar(64) NOT NULL,
    name          varchar(200) NOT NULL,
    branch_type   varchar(32) NOT NULL DEFAULT 'branch',  -- branch | depot | yard
    region        varchar(120),
    address       varchar(300),
    city          varchar(120),
    state         varchar(120),
    country_code  varchar(8),
    timezone      varchar(64),
    manager_user_id bigint,
    status        varchar(32) NOT NULL DEFAULT 'Active',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz,
    deleted_at    timestamptz,
    UNIQUE (company_id, branch_code)
);
CREATE INDEX IF NOT EXISTS idx_branches_company ON branches (company_id);

ALTER TABLE users    ADD COLUMN IF NOT EXISTS branch_id bigint;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS branch_id bigint;
ALTER TABLE drivers  ADD COLUMN IF NOT EXISTS branch_id bigint;
CREATE INDEX IF NOT EXISTS idx_users_branch    ON users (branch_id)    WHERE branch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vehicles_branch ON vehicles (branch_id) WHERE branch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_drivers_branch  ON drivers (branch_id)  WHERE branch_id IS NOT NULL;

COMMIT;
