import type { IntegrationRecord } from "./integrations.types";

export const integrationCatalog: Omit<IntegrationRecord, "tenantId">[] = [
  {
    id: 1,
    key: "sap-s4hana",
    name: "SAP S/4HANA",
    category: "ERP & Accounting",
    description: "Order, invoice, GL posting, and cost-center synchronization for enterprise finance.",
    logo: "SAP",
    status: "Connected",
    sync: "2 min ago",
    lastSyncAt: "2026-06-24T14:11:00Z",
    relatedSystems: ["orders", "invoices", "ledger"],
    connectedTo: ["ERP", "Accounting"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: { baseUrl: "https://sap.example.com", companyCode: "NSFL" },
  },
  {
    id: 2,
    key: "oracle-netsuite",
    name: "Oracle NetSuite",
    category: "ERP & Accounting",
    description: "Cloud ERP for financials, inventory, and multi-subsidiary accounting.",
    logo: "ORA",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["ledger", "inventory"],
    connectedTo: ["ERP"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 3,
    key: "microsoft-dynamics",
    name: "Microsoft Dynamics 365",
    category: "ERP & Accounting",
    description: "ERP + CRM synchronization for finance, orders, and service workflows.",
    logo: "MS",
    status: "Pending",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["crm", "orders", "billing"],
    connectedTo: ["ERP", "CRM"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 4,
    key: "quickbooks-online",
    name: "QuickBooks Online",
    category: "ERP & Accounting",
    description: "SMB accounting, expense sync, and invoice posting for smaller fleets.",
    logo: "QB",
    status: "Connected",
    sync: "5 min ago",
    lastSyncAt: "2026-06-24T14:08:00Z",
    relatedSystems: ["invoices", "expenses"],
    connectedTo: ["Accounting"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: { companyId: "qb-northshore" },
  },
  {
    id: 5,
    key: "xero",
    name: "Xero",
    category: "ERP & Accounting",
    description: "Online accounting with bank reconciliation and multi-currency reporting.",
    logo: "XER",
    status: "Error",
    sync: "14h ago",
    lastSyncAt: "2026-06-23T23:18:00Z",
    relatedSystems: ["invoices", "payments"],
    connectedTo: ["Accounting"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 6,
    key: "sage-intacct",
    name: "Sage Intacct",
    category: "ERP & Accounting",
    description: "Cloud financial management for revenue recognition and project accounting.",
    logo: "SGE",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["finance"],
    connectedTo: ["Accounting"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 7,
    key: "samsara",
    name: "Samsara",
    category: "Telematics & ELD",
    description: "GPS tracking, ELD, and AI dashcam event integration for live fleet operations.",
    logo: "SAM",
    status: "Connected",
    sync: "Real-time",
    lastSyncAt: "2026-06-24T14:14:00Z",
    relatedSystems: ["vehicles", "drivers", "safety"],
    connectedTo: ["GPS", "ELD", "Dashcam"],
    managedBy: "Fleet Ops",
    scope: "tenant",
    config: { providerAccountId: "sam-1001" },
  },
  {
    id: 8,
    key: "geotab",
    name: "Geotab",
    category: "Telematics & ELD",
    description: "Fleet telematics and open SDK for GPS, diagnostics, and log data.",
    logo: "GEO",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["vehicles", "diagnostics"],
    connectedTo: ["GPS", "Diagnostics"],
    managedBy: "Fleet Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 9,
    key: "verizon-connect",
    name: "Verizon Connect",
    category: "Telematics & ELD",
    description: "Fleet tracking and dispatch telemetry for location and duty status.",
    logo: "VZN",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["dispatch", "location"],
    connectedTo: ["GPS"],
    managedBy: "Fleet Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 10,
    key: "motive",
    name: "Motive",
    category: "Telematics & ELD",
    description: "ELD, DVIR, and driver safety event integration for regulated fleets.",
    logo: "MOT",
    status: "Pending",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["eld", "dvir", "safety"],
    connectedTo: ["ELD", "Dashcam"],
    managedBy: "Fleet Ops",
    scope: "tenant",
    config: { webhookUrl: "" },
  },
  {
    id: 11,
    key: "platform-science",
    name: "Platform Science",
    category: "Telematics & ELD",
    description: "Carrier platform for driver apps, dispatch, and compliance workflows.",
    logo: "PS",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["driver-app", "dispatch"],
    connectedTo: ["ELD"],
    managedBy: "Fleet Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 12,
    key: "wex-fuel-card",
    name: "WEX Fuel Card",
    category: "Fuel Cards",
    description: "Fuel transactions, odometer capture, and anomaly detection sync.",
    logo: "WEX",
    status: "Connected",
    sync: "1 min ago",
    lastSyncAt: "2026-06-24T14:15:00Z",
    relatedSystems: ["fuel", "cost"],
    connectedTo: ["Fuel"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: { accountId: "wex-88231" },
  },
  {
    id: 13,
    key: "fleetcor",
    name: "Fleetcor / Corpay",
    category: "Fuel Cards",
    description: "Fuel and spend controls with vehicle-level transaction visibility.",
    logo: "FLC",
    status: "Pending",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["fuel", "spend-controls"],
    connectedTo: ["Fuel"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 14,
    key: "comdata",
    name: "Comdata",
    category: "Fuel Cards",
    description: "Fuel, toll, and cash card transaction network integration.",
    logo: "CMD",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["fuel", "tolls"],
    connectedTo: ["Fuel"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 15,
    key: "shell-fleet",
    name: "Shell Fleet",
    category: "Fuel Cards",
    description: "Global fuel card support with international fleet transaction feeds.",
    logo: "SHL",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["fuel", "international"],
    connectedTo: ["Fuel"],
    managedBy: "Finance Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 16,
    key: "google-maps-platform",
    name: "Google Maps Platform",
    category: "Maps & Routing",
    description: "Routing, geocoding, distance matrix, and live traffic for dispatch planning.",
    logo: "GGL",
    status: "Connected",
    sync: "Active",
    lastSyncAt: "2026-06-24T14:13:00Z",
    relatedSystems: ["routes", "eta", "geocoding"],
    connectedTo: ["Maps", "Routing"],
    managedBy: "Dispatch Ops",
    scope: "tenant",
    config: { apiKey: "maps-***" },
  },
  {
    id: 17,
    key: "here-maps",
    name: "HERE Maps",
    category: "Maps & Routing",
    description: "Truck routing and coverage for regional operations.",
    logo: "HRE",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["routes", "eta"],
    connectedTo: ["Maps"],
    managedBy: "Dispatch Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 18,
    key: "mapbox",
    name: "Mapbox",
    category: "Maps & Routing",
    description: "Customizable live maps for vehicle tracking and geo overlays.",
    logo: "MPB",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["live-map", "geofences"],
    connectedTo: ["Maps"],
    managedBy: "Dispatch Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 19,
    key: "ptv-route-optimiser",
    name: "PTV Route Optimiser",
    category: "Maps & Routing",
    description: "Multi-stop route optimization with vehicle and time-window constraints.",
    logo: "PTV",
    status: "Pending",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["route-plans", "dispatch"],
    connectedTo: ["Routing"],
    managedBy: "Dispatch Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 20,
    key: "whatsapp-business",
    name: "WhatsApp Business API",
    category: "Messaging & Notifications",
    description: "Customer ETA, delay, and delivery notifications via WhatsApp.",
    logo: "WA",
    status: "Connected",
    sync: "Just now",
    lastSyncAt: "2026-06-24T14:16:00Z",
    relatedSystems: ["customer-notifications", "eta"],
    connectedTo: ["Messaging"],
    managedBy: "Ops Communications",
    scope: "tenant",
    config: { sender: "OpsTrax" },
  },
  {
    id: 21,
    key: "twilio-sms",
    name: "Twilio SMS",
    category: "Messaging & Notifications",
    description: "SMS delivery for driver and customer communications.",
    logo: "TWL",
    status: "Connected",
    sync: "8 min ago",
    lastSyncAt: "2026-06-24T14:07:00Z",
    relatedSystems: ["sms", "driver-alerts"],
    connectedTo: ["Messaging"],
    managedBy: "Ops Communications",
    scope: "tenant",
    config: { sender: "OpsTrax" },
  },
  {
    id: 22,
    key: "slack",
    name: "Slack",
    category: "Messaging & Notifications",
    description: "Critical alerting and operational notifications into Slack channels.",
    logo: "SLK",
    status: "Connected",
    sync: "3 min ago",
    lastSyncAt: "2026-06-24T14:12:00Z",
    relatedSystems: ["alerts", "escalations"],
    connectedTo: ["Messaging"],
    managedBy: "Ops Communications",
    scope: "tenant",
    config: { channel: "#ops" },
  },
  {
    id: 23,
    key: "microsoft-teams",
    name: "Microsoft Teams",
    category: "Messaging & Notifications",
    description: "Enterprise channel alerts for operations and compliance teams.",
    logo: "MST",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["alerts", "compliance"],
    connectedTo: ["Messaging"],
    managedBy: "Ops Communications",
    scope: "tenant",
    config: {},
  },
  {
    id: 24,
    key: "sendgrid-email",
    name: "SendGrid Email",
    category: "Messaging & Notifications",
    description: "Transactional email for invoices, reports, and compliance notices.",
    logo: "SG",
    status: "Connected",
    sync: "12 min ago",
    lastSyncAt: "2026-06-24T14:04:00Z",
    relatedSystems: ["reports", "notices", "invoices"],
    connectedTo: ["Messaging"],
    managedBy: "Ops Communications",
    scope: "tenant",
    config: { sender: "ops@opstrax.com" },
  },
  {
    id: 25,
    key: "sap-extended-wms",
    name: "SAP Extended WMS",
    category: "WMS & Shipment Ops",
    description: "Warehouse pick, pack, and carrier booking synchronization.",
    logo: "SWMS",
    status: "Connected",
    sync: "4 min ago",
    lastSyncAt: "2026-06-24T14:09:00Z",
    relatedSystems: ["warehouse", "shipments"],
    connectedTo: ["WMS"],
    managedBy: "Supply Chain Ops",
    scope: "tenant",
    config: { warehouseCode: "DC-01" },
  },
  {
    id: 26,
    key: "manhattan-wms",
    name: "Manhattan WMS",
    category: "WMS & Shipment Ops",
    description: "Enterprise warehouse execution and labor management integration.",
    logo: "MWM",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["warehouse", "labor"],
    connectedTo: ["WMS"],
    managedBy: "Supply Chain Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 27,
    key: "aws-iot-core",
    name: "AWS IoT Core",
    category: "IoT & Sensors",
    description: "Message broker for sensor telemetry and device shadow state.",
    logo: "AWS",
    status: "Connected",
    sync: "Real-time",
    lastSyncAt: "2026-06-24T14:16:00Z",
    relatedSystems: ["telemetry", "sensors"],
    connectedTo: ["IoT"],
    managedBy: "Telematics Ops",
    scope: "tenant",
    config: { topicPrefix: "opstrax/fleet" },
  },
  {
    id: 28,
    key: "azure-iot-hub",
    name: "Azure IoT Hub",
    category: "IoT & Sensors",
    description: "Enterprise IoT gateway with device management and stream analytics.",
    logo: "AZR",
    status: "Disconnected",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["telemetry", "devices"],
    connectedTo: ["IoT"],
    managedBy: "Telematics Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 29,
    key: "trimble-tmt",
    name: "Trimble TMT",
    category: "IoT & Sensors",
    description: "Maintenance and device telemetry feed for fleet health workflows.",
    logo: "TMB",
    status: "Pending",
    sync: "—",
    lastSyncAt: null,
    relatedSystems: ["maintenance", "telemetry"],
    connectedTo: ["IoT", "Maintenance"],
    managedBy: "Telematics Ops",
    scope: "tenant",
    config: {},
  },
  {
    id: 30,
    key: "fmcsa-portal",
    name: "FMCSA Portal",
    category: "Compliance",
    description: "Compliance data exchange for carrier authority and safety visibility.",
    logo: "FMC",
    status: "Connected",
    sync: "Daily",
    lastSyncAt: "2026-06-24T09:00:00Z",
    relatedSystems: ["compliance", "safety"],
    connectedTo: ["Compliance"],
    managedBy: "Compliance Ops",
    scope: "tenant",
    config: { profile: "US FMCSA" },
  },
  {
    id: 31,
    key: "ifta-reporting",
    name: "IFTA Reporting",
    category: "Compliance",
    description: "Mileage reconciliation and quarterly IFTA filing support.",
    logo: "IFT",
    status: "Pending",
    sync: "Weekly",
    lastSyncAt: null,
    relatedSystems: ["compliance", "fuel"],
    connectedTo: ["Compliance"],
    managedBy: "Compliance Ops",
    scope: "tenant",
    config: {},
  },
];

