name: OpsTrax CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

  node-service-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
        working-directory: node-services/events

  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore
        working-directory: api-dotnet
      - run: dotnet build --no-restore
        working-directory: api-dotnet
